import { WEAPONS, UNITS, BUILDINGS, FACTIONS } from './src/data/Defs';
import { ARMOR_MATRIX, COMBAT_DAMAGE, STANCE_CHASE_METRES, STANCE_RETURNS, GUARD_LEASH, STANCE_RETURN_SLACK } from './src/core/config';
import * as cfg from './src/core/config';
(globalThis as any).__P = { WEAPONS, UNITS, BUILDINGS, FACTIONS, ARMOR_MATRIX, COMBAT_DAMAGE, STANCE_CHASE_METRES, STANCE_RETURNS, GUARD_LEASH, STANCE_RETURN_SLACK, cfg };
