/**
 * ============================================================================
 * VOLTMARCH desktop — src/main.ts
 * ============================================================================
 * THE ELECTRON MAIN PROCESS. It decides as little as possible.
 *
 * Every judgement lives in `flags.ts`, `app-url.ts` or `paths.ts`, which import
 * no electron and are unit-tested in the ordinary `npm test` gate. This file is
 * the wiring that cannot be tested without a binary, and it is deliberately
 * thin — see the Electron plan §7, and the reason: the desktop target is
 * outside CI, so the only tests that will not rot are the ones needing no
 * Electron.
 *
 * CommonJS, not ESM. Electron has supported ESM in main since v28, but ESM
 * module evaluation is asynchronous relative to app startup, and two things
 * here MUST happen before the `ready` event: `registerSchemesAsPrivileged` and
 * every `appendSwitch`. CJS makes that ordering a property of the file rather
 * than something to reason about.
 * ============================================================================
 */

import {
  app,
  BrowserWindow,
  protocol,
  net,
  shell,
  screen,
  powerSaveBlocker,
  Menu,
  ipcMain,
} from 'electron';
import path from 'node:path';
import { readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

import { DEFAULT_SETTINGS, normaliseSettings, safeModeRequested, switchesFor } from './flags';
import type { DesktopSettings } from './flags';
import { ORIGIN, SCHEME, HOST, appUrl, devOriginFromArgv, flagsFromArgv, isOwnUrl } from './app-url';
import { contentTypeFor, resolveAsset } from './paths';
import {
  DEFAULT_DISPLAY,
  applyPatch,
  displayLabel,
  normaliseDisplay,
  sizesFor,
  targetDisplay,
  windowBounds,
} from './display';
import type { DisplayInfo, DisplayPatch, DisplayPrefs, DisplayState } from './display';

/* -------------------------------------------------------------------------- */
/* 1. Where the web build lives                                                */
/* -------------------------------------------------------------------------- */

/**
 * `dist/` is the UNMODIFIED output of the root `vite build` — the same bytes
 * GitHub Pages serves. Nothing in this directory is generated by the desktop
 * build, and nothing here may modify it.
 */
const DIST = app.isPackaged
  ? path.join(process.resourcesPath, 'dist')
  : path.resolve(__dirname, '..', '..', 'dist');

/* -------------------------------------------------------------------------- */
/* 2. Settings, read before ready                                              */
/* -------------------------------------------------------------------------- */

/**
 * Read from `userData/desktop-settings.json`, before `app.whenReady()`.
 *
 * `--vm-safe-mode` skips the file entirely. That is the route back from a
 * setting that prevents the app from booting — and it has to exist, because
 * switches are appended before any window exists, so there is no in-app UI to
 * turn one off at the moment it breaks things.
 */
function settingsFile(): string {
  return path.join(app.getPath('userData'), 'desktop-settings.json');
}

/** The whole file, or `{}` when absent, unreadable or not JSON. */
function readSettingsBlob(): Record<string, unknown> {
  try {
    const raw: unknown = JSON.parse(readFileSync(settingsFile(), 'utf8'));
    return typeof raw === 'object' && raw !== null ? (raw as Record<string, unknown>) : {};
  } catch {
    // Absent or unreadable is the normal first-run case, not an error.
    return {};
  }
}

function loadSettings(): DesktopSettings {
  if (safeModeRequested(process.argv)) {
    console.log('[vm] safe mode: ignoring desktop-settings.json, no GPU switches');
    return { ...DEFAULT_SETTINGS, forceHighPerformanceGpu: false };
  }
  return normaliseSettings(readSettingsBlob());
}

function loadDisplay(): DisplayPrefs {
  /*
   * SAFE MODE COVERS THE WINDOW TOO, and that is not symmetry for its own
   * sake. `--vm-safe-mode` exists because a setting applied before any UI
   * exists can brick the boot with no in-app route back, and window placement
   * is in exactly that class: a stored monitor index that is now a display
   * which is off, unplugged or reporting bad bounds opens the window somewhere
   * the player cannot see or reach. A fullscreen window on that display is
   * worse — there is no title bar to drag.
   */
  if (safeModeRequested(process.argv)) return DEFAULT_DISPLAY;
  return normaliseDisplay(readSettingsBlob().display);
}

/**
 * Persist. Read-modify-write the whole blob rather than serialising our two
 * in-memory objects, so a key a future version adds — or one a player hand-
 * edited — is not silently dropped by an older field list.
 */
function saveSettings(next: DesktopSettings, display: DisplayPrefs): void {
  try {
    writeFileSync(
      settingsFile(),
      JSON.stringify({ ...readSettingsBlob(), ...next, display }, null, 2),
      'utf8',
    );
  } catch (err) {
    // A failed write must not take the options screen down with it.
    console.error('[vm] could not write desktop-settings.json:', err instanceof Error ? err.message : err);
  }
}

/**
 * The Vite dev server this process was told to load, or null for `app://`.
 *
 * Resolved once, at module load, because `will-navigate` and `loadURL` must
 * agree about it and re-parsing argv in two places is how they drift apart.
 */
const devOrigin = devOriginFromArgv(process.argv);

/**
 * What the process LAUNCHED with, frozen at module load.
 *
 * The comparison target for `relaunchPending`. Chromium switches were appended
 * from this object before `app.whenReady()`, so it — not whatever is now on
 * disk — is the truth about what is in force this session.
 */
const launchedWith: DesktopSettings = loadSettings();

/** Mutable current values. `launchedWith` deliberately does not track these. */
let settings: DesktopSettings = { ...launchedWith };
let display: DisplayPrefs = loadDisplay();

/* -------------------------------------------------------------------------- */
/* 3. Switches — BEFORE ready, or they are a silent no-op                      */
/* -------------------------------------------------------------------------- */

/*
 * The GPU process launches after `ready` with whatever command line the browser
 * process had AT LAUNCH. Appending later is silently ignored — no warning, no
 * log line, and the app looks like it worked.
 *
 * Measured on the RTX 3080 laptop, 2026-08-17 (RENDER_FINDINGS.md §7j): the
 * switch moves BOTH WebGL and WebGPU from amd/gcn-5 to nvidia/ampere, and
 * either spelling works alone.
 */
for (const sw of switchesFor(settings)) {
  if (sw.value === undefined) app.commandLine.appendSwitch(sw.name);
  else app.commandLine.appendSwitch(sw.name, sw.value);
}

/*
 * `registerSchemesAsPrivileged` "can only be used before the ready event... and
 * can be called only once", so it belongs at module top level.
 *
 * Every privilege here is load-bearing:
 *   standard        - a real origin. Electron's protocol docs: "By default web
 *                     storage apis (localStorage, sessionStorage, webSQL,
 *                     indexedDB, cookies) are disabled for non standard
 *                     schemes." Those appear 66 times across 20 files here.
 *                     Without it, SaveStore's IndexedDB backend is returned by
 *                     `detectBackend()` and then throws at open() time, while
 *                     `detectIndexStorage()` — which has no IndexedDB tier at
 *                     all — silently falls to MemoryIndex. Signature: saves
 *                     error on write, and the save LIST is empty next launch.
 *   secure          - `navigator.gpu` is [SecureContext]-gated. Without it the
 *                     desktop build ships with `?gpu=webgpu` permanently
 *                     unreachable through `raiseGpuFailure` — i.e. the faster
 *                     renderer, which is half the point of the wrapper.
 *   supportFetchAPI - the 184 .ogg fetches. A failure here degrades to the
 *                     synthesised bank rather than to silence, so it is
 *                     invisible without reading the console.
 *   codeCache       - V8 code cache for the 2.7 MB entry chunk.
 */
protocol.registerSchemesAsPrivileged([
  {
    scheme: SCHEME,
    privileges: {
      standard: true,
      secure: true,
      supportFetchAPI: true,
      stream: true,
      codeCache: true,
      corsEnabled: false,
      bypassCSP: false,
      allowServiceWorkers: false,
    },
  },
]);

/* -------------------------------------------------------------------------- */
/* 4. Content security policy                                                  */
/* -------------------------------------------------------------------------- */

/*
 * Delivered as a RESPONSE HEADER so `index.html` is never edited and the web
 * build stays byte-identical.
 *
 * `'unsafe-inline'` on both script and style is REQUIRED, not laziness:
 * index.html carries a pre-module inline <script> (the boot curtain and the
 * error surface — the thing that puts a readable failure on screen when the
 * bundle itself fails to parse), and `Help.ts` creates a <style> element at
 * runtime. Without it the game is a black page.
 *
 * `connect-src` allows ws:/wss: because the multiplayer relay is a WebSocket;
 * everything else is same-origin only, and there is no remote content at all.
 */
const CSP = [
  "default-src 'self'",
  "script-src 'self' 'unsafe-inline'",
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob:",
  "font-src 'self'",
  "media-src 'self' blob:",
  "connect-src 'self' ws: wss:",
  "worker-src 'self' blob:",
  "object-src 'none'",
  "base-uri 'none'",
  "frame-ancestors 'none'",
].join('; ');

/* -------------------------------------------------------------------------- */
/* 5. Serving dist/                                                            */
/* -------------------------------------------------------------------------- */

function installProtocol(): void {
  protocol.handle(SCHEME, async (request) => {
    const url = new URL(request.url);
    if (url.host !== HOST) return new Response('not found', { status: 404 });

    const abs = resolveAsset(DIST, url.pathname);
    if (abs === null) return new Response('forbidden', { status: 403 });

    const res = await net.fetch(pathToFileURL(abs).toString());
    if (!res.ok) return new Response('not found', { status: 404 });

    const headers = new Headers(res.headers);
    const type = contentTypeFor(abs);
    if (type !== null) headers.set('content-type', type);
    if (abs.endsWith('.html')) headers.set('content-security-policy', CSP);
    return new Response(res.body, { status: 200, headers });
  });
}

/* -------------------------------------------------------------------------- */
/* 6. Window                                                                   */
/* -------------------------------------------------------------------------- */

let sleepBlocker = -1;

/**
 * Flatten electron's `Display` into the shape `display.ts` reasons about.
 *
 * The pure module must not import electron, so the conversion happens here and
 * exactly here. `screen` is unavailable before `app.whenReady()`.
 */
function currentDisplays(): DisplayInfo[] {
  return screen.getAllDisplays().map((d) => ({
    id: d.id,
    label: d.label ?? '',
    width: d.size.width,
    height: d.size.height,
    workWidth: d.workArea.width,
    workHeight: d.workArea.height,
    workX: d.workArea.x,
    workY: d.workArea.y,
    primary: d.id === screen.getPrimaryDisplay().id,
  }));
}

/**
 * Put the window where the prefs say.
 *
 * THE ORDER IS LOAD-BEARING: leave fullscreen, THEN move, THEN re-enter.
 * `setFullScreen(true)` expands to whichever display the window is currently
 * on, so setting bounds on a window that is already fullscreen either fights
 * the compositor or is ignored outright. Dropping out first makes "move to
 * monitor 2 and go fullscreen" one predictable sequence instead of a race, and
 * `setFullScreen(false)` on an already-windowed window is a no-op.
 */
function applyDisplayPrefs(win: BrowserWindow, prefs: DisplayPrefs): void {
  const target = targetDisplay(prefs, currentDisplays());

  if (win.isFullScreen()) win.setFullScreen(false);

  const bounds = windowBounds(prefs, target);
  // null means "no monitor chosen" — leave the OS placement alone rather than
  // yanking the window to the centre of the primary on every launch.
  if (bounds !== null) win.setBounds(bounds);
  else if (prefs.mode === 'windowed') win.setSize(prefs.width, prefs.height);

  if (prefs.mode === 'fullscreen') win.setFullScreen(true);

  /*
   * Applied AFTER the mode, because `setFullScreen` re-stacks the window and
   * would otherwise drop the flag on the way through.
   */
  win.setAlwaysOnTop(prefs.alwaysOnTop);
}

function createWindow(): BrowserWindow {
  const initialBounds = windowBounds(display, targetDisplay(display, currentDisplays()));
  const win = new BrowserWindow({
    width: initialBounds?.width ?? display.width,
    height: initialBounds?.height ?? display.height,
    ...(initialBounds !== null ? { x: initialBounds.x, y: initialBounds.y } : {}),
    /*
     * Fullscreen is set at CONSTRUCTION rather than after `ready-to-show`.
     * Applying it later means the window is created windowed, shown, and then
     * resized — a visible jump on every launch for anyone who plays
     * fullscreen, and a resize storm through the renderer's own resize path
     * while the game is still booting.
     */
    fullscreen: display.mode === 'fullscreen',
    alwaysOnTop: display.alwaysOnTop,
    backgroundColor: '#000000',
    // The web build paints its own boot curtain; showing before first paint
    // gives a white flash on a black-backgrounded game.
    show: false,
    autoHideMenuBar: true,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
      webviewTag: false,
      /*
       * THE MULTIPLAYER FIX. Chromium calls rAF ZERO times for a hidden
       * document, `loop.ts` drives on rAF, and the lockstep step gate stalls
       * rather than skips with no client-side timeout — so one player
       * minimising freezes the match for BOTH, indefinitely. There is no
       * web-side fix for this.
       *
       * Caveat worth knowing: with this off, the Page Visibility API keeps
       * reporting `visible`, so any future `visibilitychange` pause logic
       * silently stops firing. There is none in the product path today.
       */
      backgroundThrottling: false,
    },
  });

  win.once('ready-to-show', () => win.show());

  // Do not let a game session be interrupted by the display sleeping.
  if (sleepBlocker === -1) sleepBlocker = powerSaveBlocker.start('prevent-display-sleep');

  /*
   * In dev mode this is the Vite server, so HMR works and an edit is on screen
   * without a rebuild. `dist/` is not consulted at all — which is the point,
   * and also why the packaged path must stay the default.
   */
  win.loadURL(appUrl(flagsFromArgv(process.argv), devOrigin));
  return win;
}

/* -------------------------------------------------------------------------- */
/* 6b. The bridge's other half                                                 */
/* -------------------------------------------------------------------------- */

/**
 * One handler per method exposed in `preload.ts`, and nothing else.
 *
 * Each is a narrow capability rather than a general one — `revealUserData`
 * opens exactly one known directory, not a caller-supplied path, because
 * `shell.openPath` on an arbitrary string from the renderer is a local-file
 * execution primitive.
 */
function installIpc(): void {
  ipcMain.handle('vm:version', () => app.getVersion());
  ipcMain.handle('vm:gpu-info', (_e, kind: unknown) =>
    app.getGPUInfo(kind === 'complete' ? 'complete' : 'basic'),
  );
  ipcMain.handle('vm:display-frequency', () => screen.getPrimaryDisplay().displayFrequency);
  ipcMain.handle('vm:fullscreen', (e, on: unknown) => {
    BrowserWindow.fromWebContents(e.sender)?.setFullScreen(on === true);
  });
  ipcMain.handle('vm:is-fullscreen', (e) => BrowserWindow.fromWebContents(e.sender)?.isFullScreen() ?? false);
  ipcMain.handle('vm:reveal-user-data', () => shell.openPath(app.getPath('userData')));
  ipcMain.on('vm:quit', () => app.quit());

  ipcMain.handle('vm:display-state', () => describeDisplay());
  ipcMain.handle('vm:display-set', (e, patch: unknown) => {
    const p = (typeof patch === 'object' && patch !== null ? patch : {}) as DisplayPatch;

    /*
     * TWO KINDS OF SETTING GO THROUGH ONE PATCH, and they behave differently.
     * Window mode, size and monitor apply NOW. The two switch-backed ones
     * cannot — Chromium took its command line before this window existed — so
     * they are only persisted, and `relaunchPending` is what tells the options
     * screen to say so. Silently accepting a toggle that does nothing until
     * some unstated later moment is the thing being avoided.
     */
    if (typeof p.forceHighPerformanceGpu === 'boolean' || typeof p.unlockFrameRate === 'boolean') {
      settings = normaliseSettings({
        ...settings,
        ...(typeof p.forceHighPerformanceGpu === 'boolean'
          ? { forceHighPerformanceGpu: p.forceHighPerformanceGpu }
          : {}),
        ...(typeof p.unlockFrameRate === 'boolean' ? { unlockFrameRate: p.unlockFrameRate } : {}),
      });
    }

    const before = display;
    display = applyPatch(display, p);
    saveSettings(settings, display);

    const win = BrowserWindow.fromWebContents(e.sender);
    const moved =
      before.mode !== display.mode ||
      before.width !== display.width ||
      before.height !== display.height ||
      before.displayIndex !== display.displayIndex ||
      before.alwaysOnTop !== display.alwaysOnTop;
    if (win !== null && moved) applyDisplayPrefs(win, display);

    return describeDisplay();
  });

  ipcMain.on('vm:relaunch', () => {
    /*
     * `relaunch()` ARMS a restart, it does not perform one — the new process
     * starts when this one exits, so the `quit()` is required rather than
     * belt-and-braces. argv is preserved, which is what keeps `--vm-safe-mode`
     * sticky across a relaunch made from within safe mode.
     */
    app.relaunch();
    app.quit();
  });
}

/** The single object the options screen renders its Display section from. */
function describeDisplay(): DisplayState {
  const displays = currentDisplays();
  return {
    mode: display.mode,
    width: display.width,
    height: display.height,
    displayIndex: display.displayIndex,
    alwaysOnTop: display.alwaysOnTop,
    displays: displays.map((d, i) => ({ index: i, label: displayLabel(d, i), primary: d.primary })),
    sizes: sizesFor(targetDisplay(display, displays)),
    forceHighPerformanceGpu: settings.forceHighPerformanceGpu,
    unlockFrameRate: settings.unlockFrameRate,
    // Compared against what the process LAUNCHED with, not against defaults:
    // that is the only object that reflects the switches actually in force.
    relaunchPending:
      settings.forceHighPerformanceGpu !== launchedWith.forceHighPerformanceGpu ||
      settings.unlockFrameRate !== launchedWith.unlockFrameRate,
  };
}

/* -------------------------------------------------------------------------- */
/* 7. Navigation policy                                                        */
/* -------------------------------------------------------------------------- */

/*
 * THE TRAP: copy Electron's security checklist verbatim and you break STARTING
 * A MATCH. Three renderer-initiated navigations exist in the web build and all
 * three are load-bearing:
 *
 *   Shell.ts:1890     location.assign(...)   hardLaunch — failed-rebuild escape
 *   renderer.ts:1392  location.replace(...)  the "Continue on WebGL" button
 *   renderer.ts:1395  location.replace(...)  its "Retry"
 *
 * `will-navigate` does not fire for `loadURL`, but it DOES fire for these,
 * because they are renderer-initiated. A deny-all handler kills both the WebGL
 * escape hatch and hardLaunch. Allow our own origin; refuse everything else.
 */
app.on('web-contents-created', (_event, contents) => {
  contents.on('will-navigate', (event, url) => {
    if (!isOwnUrl(url, devOrigin)) event.preventDefault();
  });
  contents.on('will-attach-webview', (event) => event.preventDefault());
  contents.setWindowOpenHandler(({ url }) => {
    // External links open in the real browser, never in a game window.
    if (/^https:\/\//.test(url)) setImmediate(() => void shell.openExternal(url));
    return { action: 'deny' };
  });
});

/* -------------------------------------------------------------------------- */
/* 8. Lifecycle                                                                */
/* -------------------------------------------------------------------------- */

// One instance. A second launch focuses the first rather than opening a rival
// window onto the same save files.
if (!app.requestSingleInstanceLock()) {
  app.quit();
} else {
  app.on('second-instance', () => {
    const [win] = BrowserWindow.getAllWindows();
    if (win !== undefined) {
      if (win.isMinimized()) win.restore();
      win.focus();
    }
  });

  // Windows taskbar grouping and notification identity.
  if (process.platform === 'win32') app.setAppUserModelId('com.three-dev.voltmarch');

  app.whenReady().then(async () => {
    Menu.setApplicationMenu(null); // an RTS has no use for a File menu
    installProtocol();
    installIpc();
    createWindow();

    /*
     * THE ENFORCEMENT PROOF. the Electron plan §1.1: the switch was
     * measured on plain Chromium, and whether Electron's appendSwitch path
     * reaches the GPU process is a separate question. Log the answer on every
     * boot so it is never assumed — and note the effect site in
     * `gpu/ipc/service/gpu_init.cc` is conjoined with `&& system_device_id_high_perf`,
     * so it can silently no-op with no log line of its own.
     *
     * getGPUInfo REJECTS outright if the GPU is disabled; do not let the probe
     * throw into a blank window.
     */
    try {
      const info = (await app.getGPUInfo('complete')) as {
        gpuDevice?: Array<{ vendorId?: number; deviceId?: number; active?: boolean }>;
      };
      const devices = info.gpuDevice ?? [];
      const active = devices.find((d) => d.active === true);
      console.log(
        `[vm] gpu: ${devices.length} adapter(s), active=` +
          (active
            ? `vendor 0x${(active.vendorId ?? 0).toString(16)} device 0x${(active.deviceId ?? 0).toString(16)}`
            : 'unknown') +
          `, forced=${settings.forceHighPerformanceGpu}`,
      );
    } catch (err) {
      console.warn('[vm] gpu info unavailable:', err instanceof Error ? err.message : err);
    }

    /*
     * WHICH ORIGIN, ON EVERY BOOT. Dev mode uses a different STORAGE origin, so
     * saves, replays and progression live in a separate profile from the
     * packaged app — usually what you want while developing, and baffling if
     * you forget. Same reasoning as logging the GPU adapter rather than
     * trusting the switch: state the thing that is easy to be wrong about.
     */
    console.log(
      devOrigin !== null
        ? `[vm] DEV MODE: loading ${devOrigin} (HMR on, separate save profile, no CSP)`
        : `[vm] loading ${ORIGIN} from ${DIST}`,
    );

    const display = screen.getPrimaryDisplay();
    // No web equivalent, which is why it is on the bridge. It IS read now, by
    // the Frame Rate Target row — but only to ANNOTATE it. See
    // `HardwareCalibration#targetMsForCap`: a 144 Hz target is inert on hardware
    // that could reach it and floors the picture on hardware that cannot, so the
    // panel does not get to choose. The player does.
    console.log(`[vm] display: ${display.size.width}x${display.size.height} @ ${display.displayFrequency}Hz`);

    app.on('activate', () => {
      if (BrowserWindow.getAllWindows().length === 0) createWindow();
    });
  });

  app.on('window-all-closed', () => {
    if (sleepBlocker !== -1 && powerSaveBlocker.isStarted(sleepBlocker)) {
      powerSaveBlocker.stop(sleepBlocker);
      sleepBlocker = -1;
    }
    if (process.platform !== 'darwin') app.quit();
  });

  // The instrument the device-loss work is missing: RENDER_FINDINGS.md §7g
  // records that no part of the WebGPU recovery path has been observed on real
  // hardware. A renderer death is now at least named.
  app.on('render-process-gone', (_e, _wc, details) => {
    console.error(`[vm] render process gone: ${details.reason} (exit ${details.exitCode})`);
  });
  app.on('child-process-gone', (_e, details) => {
    console.error(`[vm] ${details.type} process gone: ${details.reason}`);
  });
}
