/**
 * tools/brand.mjs — derive every shipped brand PNG from one source image.
 *
 *   node tools/brand.mjs                      # uses tools/brand-source/logo-source.png
 *   node tools/brand.mjs path/to/other.png    # re-derive from a replacement logo
 *
 * Writes into packages/assets/brand/, which application builds consume from one source. Everything in
 * there is generated by this script and nothing else should be put there by hand — see
 * packages/assets/brand/README.md for what each output is for.
 *
 * The source used to be read from an absolute path on one machine's Desktop, and the
 * output written to an absolute path too, so the script only ran for one person on one
 * disk. Both are resolved from this file's own location now. The source image itself was
 * living in the shipping brand directory, which meant a 2.4 MB file nothing ever loads was published to
 * GitHub Pages on every deploy; it is an input, so it lives beside the tool that reads it.
 */
import sharp from 'sharp';
import { mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = process.argv[2]
  ? resolve(process.argv[2])
  : join(ROOT, 'tools', 'brand-source', 'logo-source.png');
const OUT = join(ROOT, 'packages', 'assets', 'brand');

if (!existsSync(SRC)) {
  console.error(`no source image at ${SRC}`);
  console.error('pass one as the first argument, or restore tools/brand-source/logo-source.png');
  process.exit(1);
}
mkdirSync(OUT, { recursive: true });
console.log(`source: ${SRC}`);

// Trim the transparent padding so layout can position the artwork, not the canvas.
const trimmed = await sharp(SRC).trim({ threshold: 1 }).toBuffer();
const tm = await sharp(trimmed).metadata();
const sm = await sharp(SRC).metadata();
console.log(`trimmed: ${tm.width}x${tm.height} (from ${sm.width}x${sm.height})`);

const jobs = [
  ['logo-full.png', 1400],
  ['logo-720.png', 720],
  ['logo-360.png', 360],
];
for (const [name, w] of jobs) {
  const info = await sharp(trimmed).resize({ width: w, withoutEnlargement: true })
    .png({ compressionLevel: 9, palette: false }).toFile(`${OUT}/${name}`);
  console.log(`${name}  ${info.width}x${info.height}  ${Math.round(info.size/1024)}kb`);
}

// The wordmark is unreadable below ~200px, so the app icon needs the emblem alone:
// the central bolt + wing cluster, cropped square from the upper-middle of the art.
const cx = Math.round(tm.width * 0.5);
const emblemW = Math.round(tm.width * 0.30);
const emblemH = Math.round(tm.height * 0.62);
const emblem = await sharp(trimmed)
  .extract({ left: cx - (emblemW >> 1), top: 0, width: emblemW, height: emblemH })
  .trim({ threshold: 1 }).toBuffer();
const em = await sharp(emblem).metadata();
const side = Math.max(em.width, em.height);
const square = await sharp({ create: { width: side, height: side, channels: 4, background: { r:0,g:0,b:0,alpha:0 } } })
  .composite([{ input: emblem, gravity: 'center' }]).png().toBuffer();
console.log(`emblem: ${em.width}x${em.height} -> square ${side}`);

for (const s of [512, 180, 64, 32]) {
  const info = await sharp(square).resize(s, s).png({ compressionLevel: 9 }).toFile(`${OUT}/mark-${s}.png`);
  console.log(`mark-${s}.png  ${Math.round(info.size/1024)}kb`);
}
