/**
 * ============================================================================
 * VOLTMARCH — tools/shot-compare.mjs
 * ============================================================================
 * COMPARE TWO CAPTURE SETS. The A/B half of the visual pipeline.
 *
 * `tools/metrics.mjs` scores ONE set against the bible's absolute targets, which
 * answers "is this frame right". It cannot answer "did my change do anything",
 * and CLAUDE.md asks for that question on every visual edit. The two are
 * different instruments and this is the second one.
 *
 * WHY IT EXISTS AT ALL: a change can be invisible to the scorecard and plainly
 * visible on screen. Excluding scatter props from the GTAO prepass moved the
 * weighted grade by 0.000000 and every check value by less than 1e-3, while
 * putting a ragged dark fringe along the top edge of a cafe umbrella at
 * 171/255. The scorecard is a frame-wide statistic; a prop is 40 px. Anything
 * local hides inside the average, so the average must not be the only thing
 * anybody looks at.
 *
 * Usage — `<dirA>` is the BEFORE set, `<dirB>` the AFTER:
 *
 *   node tools/shot-compare.mjs draws <dirA> <dirB>
 *       The `frame.drawCallsByPass` table out of each `_report.json`, per
 *       fixture, with deltas. No image work; instant.
 *
 *   node tools/shot-compare.mjs hot <dirA> <dirB> <fixture> [topN] [block]
 *       Rank NxN blocks by mean per-pixel delta. WHERE the change landed,
 *       answered by measurement rather than by squinting at a thumbnail. Do
 *       this before cropping — a crop chosen by eye reliably misses.
 *
 *   node tools/shot-compare.mjs crop <dirA> <dirB> <fixture> <x> <y> <w> <h> [zoom] [name]
 *       BEFORE | AFTER side by side, nearest-neighbour upscaled so a 2/255
 *       shading change is not smoothed away by the resampler, into `ab/`.
 *
 * `shots/` is regenerated by `npm run shots`, so keep a BEFORE set by copying
 * the directory aside before making the change. Both it and `ab/` are ignored.
 * ============================================================================
 */
import sharp from 'sharp';
import { mkdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

const [mode, dirA, dirB, ...rest] = process.argv.slice(2);

if (mode === undefined || dirA === undefined || dirB === undefined) {
  console.error('usage: shot-compare.mjs <draws|hot|crop> <dirA> <dirB> [...]');
  process.exit(2);
}

/** Max absolute per-channel difference over RGB. Alpha is deliberately ignored. */
function pixelDelta(a, b, i) {
  let d = 0;
  for (let c = 0; c < 3; c++) {
    const v = Math.abs(a[i + c] - b[i + c]);
    if (v > d) d = v;
  }
  return d;
}

async function raw(dir, fixture, region) {
  const s = sharp(join(dir, `${fixture}.png`));
  return (region ? s.extract(region) : s).raw().toBuffer({ resolveWithObject: true });
}

function pad(v, n) { return String(v).padStart(n); }

if (mode === 'draws') {
  const read = (d) => {
    const r = JSON.parse(readFileSync(join(d, '_report.json'), 'utf8'));
    return Object.fromEntries((r.shots ?? r).map((s) => [s.name, s.frame]));
  };
  const A = read(dirA), B = read(dirB);
  console.log(`${dirA} -> ${dirB}\n`);
  console.log('fixture'.padEnd(22) +
    ['ao A', 'ao B', 'd', '|', 'tot A', 'tot B', 'd', '|', 'col A', 'col B', 'shd A', 'shd B']
      .map((h) => pad(h, h === '|' ? 3 : 7)).join(''));
  const sum = { ao: 0, total: 0 };
  for (const name of Object.keys(A)) {
    const a = A[name], b = B[name];
    if (b === undefined) { console.log(`${name.padEnd(22)}  (absent from ${dirB})`); continue; }
    sum.ao += b.drawCallsByPass.ao - a.drawCallsByPass.ao;
    sum.total += b.drawCalls - a.drawCalls;
    console.log(name.padEnd(22) +
      pad(a.drawCallsByPass.ao, 7) + pad(b.drawCallsByPass.ao, 7) +
      pad(b.drawCallsByPass.ao - a.drawCallsByPass.ao, 7) + pad('|', 3) +
      pad(a.drawCalls, 7) + pad(b.drawCalls, 7) + pad(b.drawCalls - a.drawCalls, 7) + pad('|', 3) +
      pad(a.drawCallsByPass.colour, 7) + pad(b.drawCallsByPass.colour, 7) +
      pad(a.drawCallsByPass.shadow, 7) + pad(b.drawCallsByPass.shadow, 7));
  }
  console.log(`\nsummed over the set:  ao ${sum.ao >= 0 ? '+' : ''}${sum.ao}   ` +
    `total ${sum.total >= 0 ? '+' : ''}${sum.total}`);
} else if (mode === 'hot') {
  const [fixture, topS, blockS] = rest;
  const topN = Number(topS ?? 8);
  const BS = Number(blockS ?? 96);
  const a = await raw(dirA, fixture), b = await raw(dirB, fixture);
  const { width, height, channels } = a.info;
  const blocks = [];
  for (let by = 0; by + BS <= height; by += BS) {
    for (let bx = 0; bx + BS <= width; bx += BS) {
      let sum = 0, max = 0;
      for (let y = by; y < by + BS; y++) {
        for (let x = bx; x < bx + BS; x++) {
          const d = pixelDelta(a.data, b.data, (y * width + x) * channels);
          sum += d; if (d > max) max = d;
        }
      }
      blocks.push({ bx, by, mean: sum / (BS * BS), max });
    }
  }
  blocks.sort((p, q) => q.mean - p.mean);
  console.log(`${fixture}: top ${topN} ${BS}x${BS} blocks by mean |delta|`);
  for (const r of blocks.slice(0, topN)) {
    console.log(`  x=${r.bx} y=${r.by}   mean ${r.mean.toFixed(2)}   max ${r.max}`);
  }
} else if (mode === 'crop') {
  const [fixture, xs, ys, ws, hs, zs, name] = rest;
  const x = Number(xs), y = Number(ys), w = Number(ws), h = Number(hs);
  const zoom = Number(zs ?? 3);
  const region = { left: x, top: y, width: w, height: h };
  const a = await raw(dirA, fixture, region), b = await raw(dirB, fixture, region);
  let sum = 0, max = 0, changed = 0;
  const n = w * h;
  for (let p = 0; p < n; p++) {
    const d = pixelDelta(a.data, b.data, p * a.info.channels);
    sum += d; if (d > max) max = d; if (d > 0) changed++;
  }
  console.log(`${fixture} [${x},${y} ${w}x${h}]  mean|d| ${(sum / n).toFixed(3)}  ` +
    `max|d| ${max}  changed ${(100 * changed / n).toFixed(2)}%`);

  const up = (d) => sharp(join(d, `${fixture}.png`)).extract(region)
    // NEAREST, never the default: this exists to show a few grey levels, and a
    // smooth resample invents the gradient the crop is meant to prove or deny.
    .resize(w * zoom, h * zoom, { kernel: 'nearest' }).png().toBuffer();
  const [imgA, imgB] = await Promise.all([up(dirA), up(dirB)]);
  const GAP = 12;
  mkdirSync('ab', { recursive: true });
  const file = `${name ?? fixture}-${x}_${y}.png`;
  await sharp({
    create: {
      width: w * zoom * 2 + GAP, height: h * zoom, channels: 3,
      // Magenta: nothing in this game's palette is near it, so the seam between
      // the two panels can never be mistaken for image content.
      background: { r: 255, g: 0, b: 255 },
    },
  })
    .composite([{ input: imgA, left: 0, top: 0 }, { input: imgB, left: w * zoom + GAP, top: 0 }])
    .png().toFile(join('ab', file));
  console.log(`  -> ab/${file}   (left = ${dirA}, right = ${dirB})`);
} else {
  console.error(`unknown mode '${mode}' — expected draws, hot or crop`);
  process.exit(2);
}
