/**
 * ============================================================================
 * VOLTMARCH — src/audio/AudioEngine.ts
 * ============================================================================
 * THE MIX. Bus graph, limiter, positional playback, voice budget, ducking,
 * reverb, and the offline bake system that turns DSP recipes into AudioBuffers.
 *
 * ZERO AUDIO FILES. Every sample in this game is generated by an oscillator, a
 * noise buffer or a filter, here, in the browser, at load. Nothing is fetched
 * and nothing is decoded.
 *
 * THE ONE PERFORMANCE DECISION (VISUAL_DNA §3.1)
 * ----------------------------------------------
 * Do NOT build a nine-node graph per gunshot. At load, every one-shot is
 * rendered into N variant `AudioBuffer`s through `OfflineAudioContext`. Runtime
 * playback is `BufferSource -> gain -> panner -> bus` — four nodes, ~0.05 ms —
 * with `playbackRate` and `detune` jitter layered on top. Six baked variants
 * plus rate jitter pushes the audible repeat period past 200 firings, which is
 * the entire difference between "convincing" and "cheap".
 *
 * Only LOOPS stay as live graphs (wind, base hum, engines, music stems),
 * because they need continuous modulation that a buffer cannot express.
 *
 * WHAT THIS FILE DOES NOT DO
 * --------------------------
 * It knows nothing about the game. No EntityId, no FxKind, no events. The
 * recipes live in Weapons.ts, the announcer in Eva.ts, the sequencer in
 * Music.ts, and the wiring in audio.system.ts. This file is a mixer.
 * ============================================================================
 */

import {
  AUDIO_BUS_DB,
  AUDIO_CROWD,
  AUDIO_CULL_DB,
  AUDIO_DISTANCE,
  AUDIO_DUCK,
  AUDIO_LIMITER,
  AUDIO_MASTER_GAIN,
  AUDIO_MAX_LOOPS,
  AUDIO_MAX_ONESHOTS,
  AUDIO_REVERB,
  AUDIO_REVERB_CROSSFADE_SEC,
  AUDIO_SAMPLE_RATE,
  AUDIO_SOFTCLIP_K,
  AUDIO_SOFTCLIP_POINTS,
  AUDIO_STEAL_RAMP_MS,
  AUDIO_VOICE_CAPS,
} from '../core/config';
import { SampleBank, sampleInto, variantDetune } from './Samples';

/* ==========================================================================
 * 1. SMALL MATH — no imports from core/math so this file stays standalone-safe
 *    (it is constructed before the game context exists).
 * ========================================================================== */

/** dBFS -> linear amplitude. -Infinity maps to exactly 0. */
export function dbToGain(db: number): number {
  return db <= -200 ? 0 : Math.pow(10, db / 20);
}

/** Linear amplitude -> dBFS. 0 maps to -200 rather than -Infinity. */
export function gainToDb(g: number): number {
  return g <= 1e-10 ? -200 : 20 * Math.log10(g);
}

export function clamp(v: number, lo: number, hi: number): number {
  return v < lo ? lo : v > hi ? hi : v;
}

/**
 * SFX bus glue. Owned here rather than in config.ts because it is not a taste
 * knob: these values exist to stop twenty simultaneous transients from summing
 * into the master limiter, and they were set by measuring that case.
 */
const SFX_GLUE = {
  threshold: -20, knee: 6, ratio: 3, attack: 0.006, release: 0.22, makeupDb: 4.5,
} as const;

/** Return level of the wide (explosion) room. Quieter than the close one. */
const WIDE_RETURN_DB = -19;

/** The wide room's decay, as a multiple of the theatre's own RT60. */
const WIDE_RT_SCALE = 2.4;

/**
 * Per-band decay multipliers for a procedural IR: low, mid, high.
 *
 * Real rooms absorb treble far faster than bass — that frequency-dependent
 * decay IS the perception of a space. A single-envelope noise burst decays at
 * one rate across the spectrum and sounds like a noise burst, which is what the
 * previous implementation was.
 */
const IR_BAND_DECAY = [1.0, 0.72, 0.42] as const;

/** A seeded uniform [0,1). Bakes must be reproducible across reloads. */
export type Rng01 = () => number;

/** mulberry32 — 32-bit, fast, good enough for noise and jitter. */
export function makeRng(seed: number): Rng01 {
  let a = seed >>> 0;
  return () => {
    a = (a + 0x6d2b79f5) >>> 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

/** Uniform in [lo,hi). */
export function rand(rng: Rng01, lo: number, hi: number): number {
  return lo + rng() * (hi - lo);
}

/* ==========================================================================
 * 2. BAKE HELPERS
 *
 * Everything a recipe needs to describe a sound as nodes. They are plain
 * functions rather than a class so a recipe reads like the spec table it came
 * from: `layer(oc, ...)` top to bottom, one line per row.
 * ========================================================================== */

/** Buffers every recipe may draw on. Generated once, shared by all bakes. */
export interface BakeKit {
  /** 2 s of white noise, mono, seeded. */
  white: AudioBuffer;
  /** 10 s of Voss-McCartney pink noise (6 octaves), mono, seeded. */
  pink: AudioBuffer;
  /** The offline context the recipe is rendering into. */
  oc: OfflineAudioContext;
  /**
   * WHERE A RECIPE CONNECTS. Not `oc.destination`.
   *
   * The bake wires this through a 4x-oversampled saturator (`SoundSpec.drive`)
   * before the destination, so every layer of every sound shares one non-linear
   * stage. That is not a polish detail: a sum of clean oscillators and filtered
   * noise measures at a 22 dB crest factor and reads as a toy, because nothing
   * in the physical world gets loud without something in the chain bending.
   * Routing through here is what buys back ~8 dB of RMS at the same peak.
   */
  out: AudioNode;
  /** Deterministic per-variant RNG. */
  rng: Rng01;
  /** Which variant (0..variants-1) is being rendered. */
  variant: number;
}

/**
 * Generate white noise into a mono AudioBuffer using an OfflineAudioContext
 * as a buffer factory (any BaseAudioContext can create buffers).
 */
export function makeWhiteNoise(ac: BaseAudioContext, seconds: number, seed: number): AudioBuffer {
  const n = Math.max(1, Math.floor(seconds * ac.sampleRate));
  const buf = ac.createBuffer(1, n, ac.sampleRate);
  const d = buf.getChannelData(0);
  const rng = makeRng(seed);
  for (let i = 0; i < n; i++) d[i] = rng() * 2 - 1;
  return buf;
}

/**
 * Voss-McCartney pink noise: 6 octave generators, each re-rolled at half the
 * rate of the previous one. Cheap, and the 1/f slope is what makes wind and
 * explosion tails sound like air rather than static.
 */
export function makePinkNoise(ac: BaseAudioContext, seconds: number, seed: number): AudioBuffer {
  const n = Math.max(1, Math.floor(seconds * ac.sampleRate));
  const buf = ac.createBuffer(1, n, ac.sampleRate);
  const d = buf.getChannelData(0);
  const rng = makeRng(seed);
  const OCT = 6;
  const rows = new Float32Array(OCT);
  for (let i = 0; i < OCT; i++) rows[i] = rng() * 2 - 1;
  let running = 0;
  for (let i = 0; i < OCT; i++) running += rows[i];
  let counter = 0;
  let peak = 1e-6;
  for (let i = 0; i < n; i++) {
    counter++;
    // The index of the lowest set bit selects which octave re-rolls.
    let bit = 0;
    let c = counter;
    while ((c & 1) === 0 && bit < OCT - 1) { c >>= 1; bit++; }
    running -= rows[bit];
    rows[bit] = rng() * 2 - 1;
    running += rows[bit];
    const v = running / OCT;
    d[i] = v;
    const a = v < 0 ? -v : v;
    if (a > peak) peak = a;
  }
  const norm = 0.95 / peak;
  for (let i = 0; i < n; i++) d[i] *= norm;
  return buf;
}

/** A noise source that starts at a random offset so variants never align. */
export function noiseSrc(kit: BakeKit, buf: AudioBuffer, when: number, dur: number): AudioBufferSourceNode {
  const s = kit.oc.createBufferSource();
  s.buffer = buf;
  s.loop = true;
  const offset = kit.rng() * Math.max(0.001, buf.duration - 0.05);
  s.start(when, offset, dur + 0.02);
  s.stop(when + dur + 0.02);
  return s;
}

/** A gain node preset to a linear value. */
export function gain(oc: BaseAudioContext, v: number): GainNode {
  const g = oc.createGain();
  g.gain.value = v;
  return g;
}

/** A biquad. `q` and `gainDb` are ignored by filter types that do not use them. */
export function biquad(
  oc: BaseAudioContext, type: BiquadFilterType, freq: number, q = 1, gainDb = 0,
): BiquadFilterNode {
  const f = oc.createBiquadFilter();
  f.type = type;
  f.frequency.value = freq;
  f.Q.value = q;
  f.gain.value = gainDb;
  return f;
}

/** An oscillator, started and stopped for you. */
export function osc(
  oc: BaseAudioContext, type: OscillatorType, freq: number, when: number, dur: number,
): OscillatorNode {
  const o = oc.createOscillator();
  o.type = type;
  o.frequency.value = freq;
  o.start(when);
  o.stop(when + dur + 0.02);
  return o;
}

/**
 * Percussive amplitude envelope: linear attack to `peak`, exponential decay.
 *
 * `peak` is RELATIVE to the param's current value, and that is the whole point.
 * Every recipe in this codebase is written as
 *
 *     const g = gain(oc, dbToGain(-16));   // "this layer sits at -16 dB"
 *     env(g.gain, t, 1, 1.0, 750);
 *
 * and while this function ASSIGNED an absolute value, the entire first line was
 * dead code: the schedule overwrote it and the layer played at unity. Every
 * layer of every sound in the bank was therefore at the same level, and the
 * carefully written balance in each recipe's doc comment described something
 * that had never been rendered. That is why the measured spectra bore so little
 * relation to the intent — an explosion's -12 dB rumble bed was as loud as its
 * body, and a UI click's -16 dB thump was as loud as its click.
 *
 * Reading `p.value` first makes the trim mean what it says, at every existing
 * call site, without touching one of them.
 *
 * NEVER `exponentialRampToValueAtTime(0)` — the Web Audio spec throws on a zero
 * target. Ramp to a small epsilon, then hard-zero.
 */
export function env(
  p: AudioParam, when: number, attackMs: number, peak: number, decayMs: number,
): void {
  const a = Math.max(0.0002, attackMs / 1000);
  const d = Math.max(0.002, decayMs / 1000);
  const top = Math.max(1e-5, peak * p.value);
  const floor = Math.min(1e-5, top * 1e-4);
  p.setValueAtTime(floor, when);
  p.linearRampToValueAtTime(top, when + a);
  p.exponentialRampToValueAtTime(floor, when + a + d);
  p.setValueAtTime(0, when + a + d);
}

/**
 * ADSR-ish envelope with a sustain shelf. Used by brass stabs and voiced
 * phonemes where a pure percussive decay reads as a pluck.
 */
export function envSustain(
  p: AudioParam, when: number,
  attackMs: number, peak: number, decayMs: number, sustain: number,
  holdMs: number, releaseMs: number,
): void {
  const a = Math.max(0.0002, attackMs / 1000);
  const d = Math.max(0.001, decayMs / 1000);
  const h = Math.max(0, holdMs / 1000);
  const r = Math.max(0.002, releaseMs / 1000);
  // Relative to the param's constructed value — see `env` for why.
  const top = Math.max(1e-5, peak * p.value);
  const sus = Math.max(1e-5, top * sustain);
  const floor = Math.min(1e-5, top * 1e-4);
  p.setValueAtTime(floor, when);
  p.linearRampToValueAtTime(top, when + a);
  p.exponentialRampToValueAtTime(sus, when + a + d);
  p.setValueAtTime(sus, when + a + d + h);
  p.exponentialRampToValueAtTime(floor, when + a + d + h + r);
  p.setValueAtTime(0, when + a + d + h + r);
}

/** Exponential (or linear) parameter sweep, guarded against zero targets. */
export function sweep(
  p: AudioParam, when: number, from: number, to: number, ms: number, exponential = true,
): void {
  const t = Math.max(0.001, ms / 1000);
  p.setValueAtTime(Math.max(0.0001, from), when);
  if (exponential) p.exponentialRampToValueAtTime(Math.max(0.0001, to), when + t);
  else p.linearRampToValueAtTime(to, when + t);
}

/** `y = tanh(kx) / tanh(k)` transfer curve. The radio character, and the master clip. */
export function makeShaperCurve(k: number, points: number): Float32Array<ArrayBuffer> {
  const c = new Float32Array(new ArrayBuffer(points * 4));
  const norm = Math.tanh(k);
  for (let i = 0; i < points; i++) {
    const x = (i / (points - 1)) * 2 - 1;
    c[i] = Math.tanh(k * x) / norm;
  }
  return c;
}

/** A waveshaper preloaded with the tanh curve. */
export function shaper(
  oc: BaseAudioContext, k: number, oversample: OverSampleType = '2x', points = 2048,
): WaveShaperNode {
  const w = oc.createWaveShaper();
  w.curve = makeShaperCurve(k, points);
  w.oversample = oversample;
  return w;
}

/**
 * ASYMMETRIC soft clip. `asym` biases the input before the tanh, so the curve
 * compresses one half of the wave harder than the other.
 *
 * A symmetric transfer function generates ODD harmonics only — 3rd, 5th, 7th —
 * which is the sound of a fuzz pedal, not of a loud thing outdoors. Asymmetry
 * adds the EVEN harmonics (2nd, 4th) that a driven speaker cone, a microphone
 * diaphragm and the human ear all produce, and it is the difference between
 * "distorted" and "loud". The DC the bias introduces is removed by the highpass
 * every recipe's tail already sits behind.
 */
export function makeSatCurve(k: number, asym: number, points: number): Float32Array<ArrayBuffer> {
  const c = new Float32Array(new ArrayBuffer(points * 4));
  // The curve MUST pass through the origin. Centring it on the midpoint of its
  // own range instead — the obvious thing, and what this function did first —
  // maps silence to a constant +0.16, so every baked buffer carried a DC step
  // that the peak normaliser then scaled the actual sound against. Measured
  // damage: a UI click with 20% of its energy below 80 Hz and 1.6% in the band
  // it was supposed to occupy.
  // The bias is in TANH-ARGUMENT units, not input units — `tanh(kx + a)`, not
  // `tanh(k(x + a))`. Scaling the bias by the drive as well means a hard drive
  // pushes the curve so far off centre that one half of the waveform is
  // squashed 6 dB more than the other, which is not saturation, it is a
  // one-sided gate: measured, the "harder" setting produced NO loudness gain.
  const zero = Math.tanh(asym);
  const hi = Math.tanh(k + asym) - zero;
  const lo = Math.tanh(-k + asym) - zero;
  const norm = Math.max(Math.abs(hi), Math.abs(lo));
  for (let i = 0; i < points; i++) {
    const x = (i / (points - 1)) * 2 - 1;
    c[i] = (Math.tanh(k * x + asym) - zero) / norm;
  }
  return c;
}

/** A waveshaper with the asymmetric curve, oversampled so it does not alias. */
export function saturator(
  oc: BaseAudioContext, k: number, asym = 0.12, oversample: OverSampleType = '4x',
): WaveShaperNode {
  const w = oc.createWaveShaper();
  w.curve = makeSatCurve(k, asym, 2048);
  w.oversample = oversample;
  return w;
}

/* --------------------------------------------------------------------------
 * THE THREE-LAYER MODEL
 *
 * Every percussive sound in this game is built from the same three elements,
 * because that is what a real report is:
 *
 *   1. TRANSIENT  0-8 ms. Very short, very bright. This is the mechanism — the
 *      firing pin, the shell splitting, metal on metal. Without it a sound has
 *      no point of origin and reads as a synth patch.
 *   2. BODY       20-200 ms. A pitched thump whose frequency sweeps DOWNWARD.
 *      The downward sweep is the single most important trick in the file: the
 *      SAME oscillator at a fixed pitch is a beep, and swept 180 -> 45 Hz it is
 *      an explosion. Nothing else produces that read.
 *   3. TAIL       150 ms - 2.5 s. Filtered noise decaying into the reverb send.
 *      This is the room. A sound with no tail is dry and toy-like however good
 *      the first two layers are, and dryness was the loudest defect in the
 *      measured baseline (T40 of 0.15 s on a tank cannon).
 *
 * The helpers below are those three rows, so a recipe reads as the spec table
 * it came from rather than as forty lines of node plumbing.
 * -------------------------------------------------------------------------- */

/**
 * Layer 1. A highpassed noise click, `ms` long, with a near-instant attack.
 * `hz` is the highpass corner: 2-4 kHz for a rifle, 800 Hz for something heavy.
 */
export function transient(
  kit: BakeKit, when: number, db: number, hz: number, ms: number, q = 0.7,
): void {
  const { oc } = kit;
  const g = gain(oc, dbToGain(db));
  const hp = biquad(oc, 'highpass', hz, q);
  env(g.gain, when, 0.35, 1.0, ms);
  noiseSrc(kit, kit.white, when, ms / 1000 + 0.01).connect(hp).connect(g).connect(kit.out);
}

/**
 * Layer 2. A pitched body sweeping `fromHz -> toHz` over `sweepMs`, decaying
 * over `decayMs`. `type` picks the harmonic content: sine for pure weight,
 * triangle for a little bite, square for a mechanical thump.
 */
export function bodyDrop(
  kit: BakeKit, when: number, db: number,
  fromHz: number, toHz: number, sweepMs: number, decayMs: number,
  type: OscillatorType = 'sine', attackMs = 1.2,
): void {
  const { oc } = kit;
  const g = gain(oc, dbToGain(db));
  const o = osc(oc, type, fromHz, when, (decayMs + sweepMs) / 1000 + 0.05);
  sweep(o.frequency, when, fromHz, toHz, sweepMs);
  env(g.gain, when, attackMs, 1.0, decayMs);
  o.connect(g).connect(kit.out);
}

/**
 * Layer 3. Decaying filtered noise: the room. `lpFrom -> lpTo` is the air
 * absorption of the report bouncing off the terrain, so it darkens as it dies.
 *
 * `preMs` delays the tail behind the transient. A tail that starts at t=0 is
 * part of the attack and stops reading as a reflection — 12-40 ms of gap is
 * what makes a sound feel like it happened somewhere.
 */
export function tail(
  kit: BakeKit, when: number, db: number,
  lpFrom: number, lpTo: number, decayMs: number, preMs = 18, hpHz = 90,
): void {
  const { oc } = kit;
  const t = when + preMs / 1000;
  const g = gain(oc, dbToGain(db));
  const lp = biquad(oc, 'lowpass', lpFrom, 0.6);
  sweep(lp.frequency, t, lpFrom, lpTo, decayMs * 0.8);
  const hp = biquad(oc, 'highpass', hpHz, 0.5);
  env(g.gain, t, Math.min(30, decayMs * 0.08), 1.0, decayMs);
  noiseSrc(kit, kit.pink, t, decayMs / 1000 + 0.05).connect(lp).connect(hp).connect(g).connect(kit.out);
}

/**
 * A ring modulator. WebAudio has no multiply node, so the carrier is routed
 * into the *gain* AudioParam of a GainNode whose base value is 0 — an audio-rate
 * connection to an AudioParam is addition, and with base 0 that is a product.
 */
export function ringMod(
  oc: BaseAudioContext, carrierHz: number, when: number, dur: number, wet: number,
): { input: GainNode; output: GainNode } {
  const input = gain(oc, 1);
  const output = gain(oc, 1);
  // dry path
  const dry = gain(oc, 1 - wet);
  input.connect(dry).connect(output);
  // wet path: multiply by the carrier
  const mul = gain(oc, 0);
  mul.gain.value = 0;
  const c = osc(oc, 'sine', carrierHz, when, dur);
  c.connect(mul.gain);
  const wetGain = gain(oc, wet);
  input.connect(mul).connect(wetGain).connect(output);
  return { input, output };
}

/* ==========================================================================
 * 3. SOUND REGISTRATION
 * ========================================================================== */

export type BusName = 'music' | 'sfx' | 'voice' | 'ui' | 'ambience';

export type VoiceCategory =
  | 'gunfire' | 'explosion' | 'tesla' | 'rocket'
  | 'engine' | 'footstep' | 'ui' | 'voice' | 'misc';

/** One bakeable one-shot. `render` describes the sound; the engine owns the rest. */
export interface SoundSpec {
  /** Stable id used by `play`. */
  readonly id: string;
  readonly bus: BusName;
  readonly category: VoiceCategory;
  /** Peak level at the bus input, in dBFS. */
  readonly db: number;
  /** How many distinct bakes to render. More variants = longer repeat period. */
  readonly variants: number;
  /** Buffer length in seconds. Anything past this is truncated by the render. */
  readonly seconds: number;
  /** 1 for anything that gets panned (halves memory), 2 for UI and music beds. */
  readonly channels?: number;
  /** playbackRate is randomised in [1-rateJitter, 1+rateJitter] per firing. */
  readonly rateJitter?: number;
  /** Reverb send in dB for the non-positional case. -200 disables the send. */
  readonly sendDb?: number;
  /**
   * Which room this sound is in. `close` is the tight outdoor slap every weapon
   * and impact wants; `wide` is the long IR reserved for explosions, so a boom
   * gets a real horizon while a rifle does not sound like it is in a cathedral.
   */
  readonly reverb?: 'close' | 'wide';
  /**
   * Bake-time saturation, as the `k` of `tanh(kx)`. 0 disables the stage.
   *
   * This is applied to the SUM of the recipe's layers through `kit.out`, 4x
   * oversampled. Typical values: 1.4 for something that only needs gluing, 2.6
   * for a cannon, 3.5 for an explosion that should sound like it overloaded the
   * microphone. Measured effect on a tank cannon: crest 24.0 dB -> 15.6 dB at
   * the same peak, which is +8 dB of loudness for free.
   */
  readonly drive?: number;
  /** Asymmetry of the saturation curve — see `makeSatCurve`. */
  readonly driveAsym?: number;
  /** False for UI: no pan, no distance, no cull. */
  readonly positional?: boolean;
  /** True to skip crowd summation (UI, voice — a volley of clicks is wrong). */
  readonly noCrowd?: boolean;
  /**
   * Peak-normalise the variant set to 1.0 after rendering (default true), so
   * `db` above is literally the peak dBFS this sound reaches at the bus input.
   * Set false only for a bed whose absolute level is itself the point.
   */
  readonly normalize?: boolean;
  /**
   * Sample family in `SAMPLE_MANIFEST`. When its files are on disk and decoded,
   * a recorded take replaces `render` for every variant of this sound.
   *
   * `render` STAYS REQUIRED even here, and that is the point: a 404, an offline
   * player or a container the browser will not decode falls back to the recipe,
   * so the failure mode is "the old bank" and never silence.
   */
  readonly sample?: string;
  /**
   * dB trim on the take before the shared saturator. The packs are internally
   * consistent but not consistent with EACH OTHER, and since normalisation runs
   * after the saturator a hot take comes out a different shape, not just louder.
   */
  readonly sampleDb?: number;
  /** Renders one variant. `kit.oc.destination` is the buffer. */
  render(kit: BakeKit): void;
}

interface BakedSound {
  spec: SoundSpec;
  buffers: AudioBuffer[];
  /** Round-robin cursor so consecutive firings never pick the same bake twice. */
  cursor: number;
  /* -- crowd summation window -- */
  windowStart: number;
  windowCount: number;
  windowX: number;
  windowY: number;
  windowZ: number;
  volleyEmitted: boolean;
}

/* ==========================================================================
 * 4. BUSES AND DUCKING
 * ========================================================================== */

interface BusStrip {
  /** User slider x authored trim. The thing an options panel writes. */
  readonly level: GainNode;
  /** Product of every active duck. NOTHING else writes this param. */
  readonly duck: GainNode;
  /** Current product, so a release recomputes rather than guesses. */
  factors: Map<string, number>;
  /** Cached applied value, to skip redundant ramps. */
  applied: number;
}

/** A live duck. Call `release()` exactly once. */
export interface DuckHandle {
  release(): void;
}

const NULL_DUCK: DuckHandle = { release() { /* nothing to release */ } };

/* ==========================================================================
 * 5. SPATIALISATION
 *
 * The engine never looks at a camera. `audio.system.ts` installs a resolver
 * that turns a world position into the four numbers the mix needs, so this file
 * has no dependency on the render stack and stays unit-testable.
 * ========================================================================== */

/**
 * Fills `out` with `[pan, distanceMetres, zoom, verticalFrac]`.
 * - `pan` is already screen-derived and clamped by the resolver.
 * - `zoom` is 1.0 at the default camera dolly, larger when pulled out.
 * - `verticalFrac` is 0 at the bottom of the playfield, 1 at the top.
 */
export type PanResolver = (x: number, y: number, z: number, out: Float32Array) => void;

const DEFAULT_RESOLVER: PanResolver = (_x, _y, _z, out) => {
  out[0] = 0; out[1] = 0; out[2] = 1; out[3] = 0.5;
};

/** Everything the mix needs to place one sound. Shared and reused — never retained. */
export interface SpatialResult {
  pan: number;
  gain: number;
  lpHz: number;
  hpHz: number;
  sendDb: number;
  distTiles: number;
  zoom: number;
}

/** Optional per-firing overrides. */
export interface PlayOptions {
  /** Extra linear gain multiplier on top of the spec level. */
  gain?: number;
  /** Explicit playbackRate; overrides the spec jitter. */
  rate?: number;
  /** Cents of detune, added to the rate jitter. */
  detune?: number;
  /** Seconds to delay the start. Used by the crowd smear. */
  delay?: number;
  /** Forces the pan, skipping the resolver. */
  pan?: number;
}

/* ==========================================================================
 * 6. VOICES
 * ========================================================================== */

interface Voice {
  src: AudioBufferSourceNode;
  amp: GainNode;
  category: VoiceCategory;
  /** Wall-clock (ctx) time the voice began. */
  startedAt: number;
  /** Final linear gain, used to pick the least audible voice to steal. */
  finalGain: number;
  stolen: boolean;
}

/**
 * A live, modulatable loop (engine, wind, hum, rocket motor). The engine owns
 * the count; the caller owns the modulation.
 */
export class LoopVoice {
  private disposed = false;

  constructor(
    private readonly engine: AudioEngine,
    /** Feed your source into this. */
    readonly input: GainNode,
    /** Level control; ramp it, do not set it. */
    readonly amp: GainNode,
    private readonly panner: StereoPannerNode | null,
    /** Sources the engine may stop and detune. Populated by attachLoopSource. */
    readonly sources: AudioScheduledSourceNode[],
    /** Nodes the caller wants to keep modulating, reachable through `node(i)`. */
    readonly extra: AudioNode[],
  ) {}

  /** Ramp to a linear gain over `ms`. */
  setGain(v: number, ms = 60): void {
    if (this.disposed) return;
    const t = this.engine.now();
    this.amp.gain.setTargetAtTime(Math.max(0, v), t, Math.max(0.005, ms / 3000));
  }

  setPan(v: number, ms = 50): void {
    if (this.disposed || this.panner === null) return;
    this.panner.pan.setTargetAtTime(clamp(v, -1, 1), this.engine.now(), Math.max(0.005, ms / 3000));
  }

  /** Reposition a moving loop: applies pan, distance gain and the tone filters. */
  setWorldPosition(x: number, y: number, z: number, baseGain: number): void {
    if (this.disposed) return;
    const s = this.engine.spatial(x, y, z);
    this.setPan(s.pan);
    this.setGain(baseGain * s.gain, 60);
  }

  /** Doppler / throttle. Cents, ramped so it never zippers. */
  setDetune(cents: number, ms = 50): void {
    if (this.disposed) return;
    const t = this.engine.now();
    for (const s of this.sources) {
      const n = s as unknown as { detune?: AudioParam };
      if (n.detune) n.detune.setTargetAtTime(clamp(cents, -1200, 1200), t, Math.max(0.005, ms / 3000));
    }
  }

  /** Playback rate on baked engine loops (throttle). */
  setRate(rate: number, ms = 80): void {
    if (this.disposed) return;
    const t = this.engine.now();
    for (const s of this.sources) {
      const n = s as unknown as { playbackRate?: AudioParam };
      if (n.playbackRate) n.playbackRate.setTargetAtTime(Math.max(0.06, rate), t, Math.max(0.005, ms / 3000));
    }
  }

  /** Any node the caller wants to keep modulating (a filter cutoff, say). */
  node(i: number): AudioNode | undefined {
    return this.extra[i];
  }

  /** Fade out and tear down. Safe to call twice. */
  stop(fadeMs = 250): void {
    if (this.disposed) return;
    this.disposed = true;
    const t = this.engine.now();
    const fade = Math.max(0.01, fadeMs / 1000);
    this.amp.gain.cancelScheduledValues(t);
    this.amp.gain.setValueAtTime(Math.max(0.0001, this.amp.gain.value), t);
    this.amp.gain.exponentialRampToValueAtTime(0.0001, t + fade);
    this.amp.gain.setValueAtTime(0, t + fade);
    for (const s of this.sources) {
      try { s.stop(t + fade + 0.02); } catch { /* already stopped */ }
    }
    this.engine.retireLoop(this, fadeMs + 60);
  }

  get alive(): boolean { return !this.disposed; }
}

/* ==========================================================================
 * 7. THE ENGINE
 * ========================================================================== */

export interface AudioEngineOptions {
  /** Screenshot mode: build the graph but never make a sound and never resume. */
  muted?: boolean;
  /** Overrides the 48 kHz default (tests). */
  sampleRate?: number;
}

export class AudioEngine {
  readonly ctx: AudioContext;
  readonly muted: boolean;

  /** The five strips, plus the reverb return. */
  private readonly strips = new Map<BusName, BusStrip>();
  private readonly master: GainNode;
  private readonly limiter: DynamicsCompressorNode;
  private readonly clipper: WaveShaperNode;
  private readonly masterDuck: GainNode;

  /** Reverb send/return. One convolver live; a second exists during a crossfade. */
  private readonly reverbSend: GainNode;
  private readonly reverbReturn: GainNode;
  private convolverA: ConvolverNode;
  private convolverB: ConvolverNode;
  private convGainA: GainNode;
  private convGainB: GainNode;
  private convUsingA = true;
  private theatre: keyof typeof AUDIO_REVERB = 'temperate';

  /**
   * The SECOND room. A rifle and a demolished war factory cannot share an
   * impulse response: the tail that makes the explosion feel like it has a
   * horizon makes the rifle sound like it was fired in a cathedral. So
   * explosions send here instead — same IR generator, 2.4x the decay.
   */
  private readonly wideSend: GainNode;
  private readonly wideReturn: GainNode;
  private readonly wideConv: ConvolverNode;

  /**
   * SFX glue. A firefight is thirty uncorrelated transients a second, and
   * without a bus compressor they simply sum until the master limiter starts
   * chewing the loudest one — which is heard as the mix ducking at random.
   * Gentle (3:1, 6 dB knee) and slow to release, so it reads as density.
   */
  private readonly sfxGlue: DynamicsCompressorNode;

  /** Baked one-shots by id. */
  private readonly sounds = new Map<string, BakedSound>();
  /** Registered but not yet baked. */
  private readonly pending: SoundSpec[] = [];

  private readonly voices: Voice[] = [];
  private readonly categoryCount = new Map<VoiceCategory, number>();
  private readonly loops: LoopVoice[] = [];

  private resolver: PanResolver = DEFAULT_RESOLVER;
  private readonly spatialOut = new Float32Array(4);
  /** Reusable spatial result — the frame loop must not allocate. */
  private readonly spatialResult: SpatialResult = {
    pan: 0, gain: 1, lpHz: AUDIO_DISTANCE.lpMaxHz, hpHz: 20, sendDb: -200, distTiles: 0, zoom: 1,
  };

  /** Shared noise beds, generated once. */
  private whiteBuf: AudioBuffer | null = null;
  private pinkBuf: AudioBuffer | null = null;

  /** Recorded CC0 takes. Empty until `loadSamples` resolves; empty is legal. */
  readonly samples = new SampleBank();

  private unlocked = false;
  private disposed = false;
  private blurTimer: ReturnType<typeof setTimeout> | null = null;
  private readonly detach: Array<() => void> = [];

  /** Diagnostics for the F3 overlay. */
  readonly stats = {
    oneShots: 0, loops: 0, stolen: 0, culled: 0, crowded: 0,
    baked: 0, bakeMs: 0, bytes: 0,
  };

  /* ---------------------------------------------------------------------- */

  /** Returns null when the platform has no WebAudio (node, old Safari kiosk). */
  static create(options: AudioEngineOptions = {}): AudioEngine | null {
    const Ctor = typeof AudioContext !== 'undefined'
      ? AudioContext
      : (globalThis as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
    if (!Ctor) return null;
    try {
      return new AudioEngine(new Ctor({
        latencyHint: 'interactive',
        sampleRate: options.sampleRate ?? AUDIO_SAMPLE_RATE,
      }), options);
    } catch {
      // Some browsers reject an explicit sampleRate. Retry with the device rate.
      try {
        return new AudioEngine(new Ctor({ latencyHint: 'interactive' }), options);
      } catch {
        return null;
      }
    }
  }

  private constructor(ctx: AudioContext, options: AudioEngineOptions) {
    this.ctx = ctx;
    this.muted = options.muted === true;

    /* -- master chain: duck -> limiter -> soft clip -> ceiling ------------- */
    this.masterDuck = gain(ctx, 1);
    this.limiter = ctx.createDynamicsCompressor();
    this.limiter.threshold.value = AUDIO_LIMITER.threshold;
    this.limiter.knee.value = AUDIO_LIMITER.knee;
    this.limiter.ratio.value = AUDIO_LIMITER.ratio;
    this.limiter.attack.value = AUDIO_LIMITER.attack;
    this.limiter.release.value = AUDIO_LIMITER.release;

    this.clipper = shaper(ctx, AUDIO_SOFTCLIP_K, '4x', AUDIO_SOFTCLIP_POINTS);
    this.master = gain(ctx, this.muted ? 0 : AUDIO_MASTER_GAIN);

    this.masterDuck.connect(this.limiter).connect(this.clipper).connect(this.master);
    this.master.connect(ctx.destination);

    /* -- five strips ------------------------------------------------------ */
    // SFX alone gets a glue compressor between its duck and the master bus.
    this.sfxGlue = ctx.createDynamicsCompressor();
    this.sfxGlue.threshold.value = SFX_GLUE.threshold;
    this.sfxGlue.knee.value = SFX_GLUE.knee;
    this.sfxGlue.ratio.value = SFX_GLUE.ratio;
    this.sfxGlue.attack.value = SFX_GLUE.attack;
    this.sfxGlue.release.value = SFX_GLUE.release;
    const glueMakeup = gain(ctx, dbToGain(SFX_GLUE.makeupDb));
    this.sfxGlue.connect(glueMakeup).connect(this.masterDuck);

    const names: BusName[] = ['music', 'sfx', 'voice', 'ui', 'ambience'];
    for (const name of names) {
      const level = gain(ctx, dbToGain(AUDIO_BUS_DB[name]));
      const duck = gain(ctx, 1);
      level.connect(duck);
      duck.connect(name === 'sfx' ? this.sfxGlue : this.masterDuck);
      this.strips.set(name, { level, duck, factors: new Map(), applied: 1 });
    }

    /* -- reverb ----------------------------------------------------------- */
    this.reverbSend = gain(ctx, 1);
    this.reverbReturn = gain(ctx, dbToGain(AUDIO_REVERB.temperate.returnDb));
    this.convolverA = ctx.createConvolver();
    this.convolverB = ctx.createConvolver();
    this.convolverA.normalize = false;
    this.convolverB.normalize = false;
    this.convGainA = gain(ctx, 1);
    this.convGainB = gain(ctx, 0);
    this.reverbSend.connect(this.convolverA).connect(this.convGainA).connect(this.reverbReturn);
    this.reverbSend.connect(this.convolverB).connect(this.convGainB).connect(this.reverbReturn);
    // The return lands on the SFX strip so the user's SFX slider governs it.
    this.reverbReturn.connect(this.strips.get('sfx')!.duck);

    /* -- the wide room, for explosions only ------------------------------- */
    this.wideSend = gain(ctx, 1);
    this.wideConv = ctx.createConvolver();
    this.wideConv.normalize = false;
    this.wideReturn = gain(ctx, dbToGain(WIDE_RETURN_DB));
    // Rolled off under 70 Hz: a long tail full of sub is mud, and the dry sub
    // of the explosion itself is already carrying the weight.
    const wideHp = biquad(ctx, 'highpass', 70, 0.6);
    this.wideSend.connect(this.wideConv).connect(wideHp).connect(this.wideReturn);
    this.wideReturn.connect(this.strips.get('sfx')!.duck);

    this.installUnlock();
    this.installVisibility();
  }

  /* ---------------------------------------------------------------------- */
  /* Lifecycle                                                              */
  /* ---------------------------------------------------------------------- */

  /** Context time. Everything schedules against this, never `Date.now()`. */
  now(): number { return this.ctx.currentTime; }

  get running(): boolean { return this.ctx.state === 'running'; }

  /**
   * Autoplay policy: a context created before a user gesture starts suspended
   * and stays that way. Resume on the first pointer/key/touch, once, then drop
   * the listeners. Silent-fail until then — never throw, never nag.
   */
  private installUnlock(): void {
    if (this.muted || typeof window === 'undefined') return;
    const tryResume = (): void => {
      if (this.unlocked || this.disposed) return;
      this.unlocked = true;
      void this.ctx.resume().catch(() => { /* user gesture rules vary; ignore */ });
      for (const off of unhook) off();
    };
    const events: Array<keyof WindowEventMap> = ['pointerdown', 'keydown', 'touchstart', 'mousedown'];
    const unhook: Array<() => void> = [];
    for (const e of events) {
      const h = (): void => tryResume();
      window.addEventListener(e, h, { passive: true });
      unhook.push(() => window.removeEventListener(e, h));
    }
    this.detach.push(() => { for (const off of unhook) off(); });
  }

  /**
   * Window blur mutes the master over 400 ms and suspends the context 2 s
   * later, so a backgrounded tab costs nothing. Focus restores both.
   */
  private installVisibility(): void {
    if (this.muted || typeof window === 'undefined') return;
    const onBlur = (): void => {
      this.duckMaster(0, AUDIO_DUCK.blurMs);
      if (this.blurTimer !== null) clearTimeout(this.blurTimer);
      this.blurTimer = setTimeout(() => {
        void this.ctx.suspend().catch(() => { /* already suspended */ });
      }, AUDIO_DUCK.blurSuspendSec * 1000);
    };
    const onFocus = (): void => {
      if (this.blurTimer !== null) { clearTimeout(this.blurTimer); this.blurTimer = null; }
      if (this.unlocked) void this.ctx.resume().catch(() => { /* ignore */ });
      this.duckMaster(1, AUDIO_DUCK.blurMs);
    };
    window.addEventListener('blur', onBlur);
    window.addEventListener('focus', onFocus);
    this.detach.push(() => {
      window.removeEventListener('blur', onBlur);
      window.removeEventListener('focus', onFocus);
    });
  }

  private duckMaster(v: number, ms: number): void {
    const t = this.now();
    this.masterDuck.gain.cancelScheduledValues(t);
    this.masterDuck.gain.setTargetAtTime(v, t, Math.max(0.01, ms / 3000));
  }

  dispose(): void {
    if (this.disposed) return;
    this.disposed = true;
    if (this.blurTimer !== null) clearTimeout(this.blurTimer);
    for (const off of this.detach) off();
    this.detach.length = 0;
    for (const l of this.loops.slice()) l.stop(20);
    for (const v of this.voices.slice()) this.killVoice(v, 0);
    this.voices.length = 0;
    this.sounds.clear();
    void this.ctx.close().catch(() => { /* already closed */ });
  }

  /* ---------------------------------------------------------------------- */
  /* Buses, sliders, ducking                                                */
  /* ---------------------------------------------------------------------- */

  /** The node a source connects to. Music/EVA/ambience all route through here. */
  busInput(name: BusName): GainNode {
    return this.strips.get(name)!.level;
  }

  /** `MusicHost`: where the sequencer's finished bed lands. */
  musicOut(): AudioNode {
    return this.busInput('music');
  }

  /** Options-panel slider, 0..100, with the perceptual 2.2 curve. */
  setBusVolume(name: BusName, percent: number): void {
    const strip = this.strips.get(name);
    if (strip === undefined) return;
    const v = Math.pow(clamp(percent, 0, 100) / 100, 2.2) * dbToGain(AUDIO_BUS_DB[name]);
    strip.level.gain.setTargetAtTime(v, this.now(), 0.02);
  }

  setMasterVolume(percent: number): void {
    if (this.muted) return;
    const v = Math.pow(clamp(percent, 0, 100) / 100, 2.2) * AUDIO_MASTER_GAIN;
    this.master.gain.setTargetAtTime(v, this.now(), 0.02);
  }

  /**
   * Multiplicative, stacked ducking. Every active duck contributes a factor;
   * the product is written to the strip's duck node in ONE `setTargetAtTime`.
   * Two callers can never fight over the param because no caller touches it.
   */
  duck(key: string, bus: BusName, amountDb: number, attackMs: number, releaseMs: number): DuckHandle {
    const strip = this.strips.get(bus);
    if (strip === undefined || this.disposed) return NULL_DUCK;
    strip.factors.set(key, dbToGain(amountDb));
    this.applyDuck(strip, attackMs);
    let released = false;
    return {
      release: () => {
        if (released || this.disposed) return;
        released = true;
        strip.factors.delete(key);
        this.applyDuck(strip, releaseMs);
      },
    };
  }

  /** A duck that releases itself after `holdMs`. The explosion case. */
  duckFor(
    key: string, bus: BusName, amountDb: number, attackMs: number, holdMs: number, releaseMs: number,
  ): void {
    const h = this.duck(key, bus, amountDb, attackMs, releaseMs);
    setTimeout(() => h.release(), Math.max(0, holdMs));
  }

  private applyDuck(strip: BusStrip, ms: number): void {
    let product = 1;
    for (const f of strip.factors.values()) product *= f;
    if (Math.abs(product - strip.applied) < 1e-4) return;
    strip.applied = product;
    strip.duck.gain.setTargetAtTime(product, this.now(), Math.max(0.005, ms / 3000));
  }

  /* ---------------------------------------------------------------------- */
  /* Spatialisation                                                         */
  /* ---------------------------------------------------------------------- */

  setPanResolver(r: PanResolver | null): void {
    this.resolver = r ?? DEFAULT_RESOLVER;
  }

  /**
   * The whole distance model in one place (§3.7). Returns a SHARED object —
   * read it immediately, never retain it. That is deliberate: this runs
   * hundreds of times a second and must not allocate.
   */
  spatial(x: number, y: number, z: number): Readonly<SpatialResult> {
    const out = this.spatialOut;
    this.resolver(x, y, z, out);
    const D = AUDIO_DISTANCE;
    const zoom = out[2] > 0 ? out[2] : 1;
    const tiles = Math.max(0, out[1]) / D.tileMetres;
    const dz = tiles * zoom;

    const r = this.spatialResult;
    r.pan = clamp(out[0], -D.panClamp, D.panClamp);
    r.distTiles = tiles;
    r.zoom = zoom;

    const k = dz / D.refTiles;
    r.gain = 1 / (1 + k * k);
    r.lpHz = clamp(D.lpMaxHz / (1 + dz / D.lpRefTiles), D.lpMinHz, D.lpMaxHz);
    r.hpHz = clamp(D.hpMinHz + dz * D.hpPerTile, D.hpMinHz, D.hpMaxHz);

    let send = D.sendNearDb + (D.sendFarDb - D.sendNearDb) * clamp(tiles / D.sendFarTiles, 0, 1);
    // Upper third of the playfield reads as further away: more room, same level.
    if (out[3] > 1 - D.upperFrac) send += D.upperSendBoostDb;
    r.sendDb = send;

    // Wide shots: trim the punch, lift the air.
    if (zoom >= D.wideZoom) r.gain *= dbToGain(D.wideSfxTrimDb);
    return r;
  }

  /* ---------------------------------------------------------------------- */
  /* Baking                                                                 */
  /* ---------------------------------------------------------------------- */

  /** Register a recipe. Nothing is rendered until `bakeAll` runs. */
  register(spec: SoundSpec): void {
    if (this.sounds.has(spec.id)) return;
    this.pending.push(spec);
  }

  has(id: string): boolean { return this.sounds.has(id); }

  /**
   * A baked variant, for callers that need the raw buffer rather than a fired
   * one-shot — engine loops (`loop = true`) and the music bed both do.
   */
  getBuffer(id: string, variant = 0): AudioBuffer | null {
    const b = this.sounds.get(id);
    if (b === undefined || b.buffers.length === 0) return null;
    return b.buffers[((variant % b.buffers.length) + b.buffers.length) % b.buffers.length];
  }

  /**
   * Render every registered recipe into buffers.
   *
   * Yields to the event loop every `sliceMs` so a 380 ms bake is four rAF
   * frames of a loading line rather than one long jank. Offline rendering runs
   * far faster than realtime, so this is dominated by promise scheduling.
   */
  async bakeAll(sliceMs = 90): Promise<void> {
    if (this.pending.length === 0) return;
    const t0 = typeof performance !== 'undefined' ? performance.now() : 0;
    this.ensureNoiseBeds();
    // Decode BEFORE the first bake. Doing it concurrently would make the source
    // of a given sound depend on which promise settled first, so a sound could
    // come out synthesised on a fast connection and recorded on a slow one —
    // non-determinism that no test would catch and every player would hear.
    await this.samples.load(this.ctx);

    let sliceStart = t0;
    const queue = this.pending.splice(0, this.pending.length);
    for (const spec of queue) {
      const baked = await this.bakeOne(spec);
      this.sounds.set(spec.id, baked);
      const nowMs = typeof performance !== 'undefined' ? performance.now() : 0;
      // Yielding exists to keep the loading screen painting. A hidden tab is
      // painting nothing AND throttles every timer to ~1 s, which turned a
      // 1.2 s bake into a measured 29 s one — so when hidden, do not yield.
      if (nowMs - sliceStart >= sliceMs && !isHidden()) {
        sliceStart = nowMs;
        await nextFrame();
      }
    }
    const t1 = typeof performance !== 'undefined' ? performance.now() : 0;
    this.stats.bakeMs += t1 - t0;
  }

  /** Bake (or re-bake) a single registered spec on demand. */
  async bake(spec: SoundSpec): Promise<void> {
    this.ensureNoiseBeds();
    this.sounds.set(spec.id, await this.bakeOne(spec));
  }

  private ensureNoiseBeds(): void {
    if (this.whiteBuf === null) this.whiteBuf = makeWhiteNoise(this.ctx, 2, 0x51ed_c0de);
    if (this.pinkBuf === null) this.pinkBuf = makePinkNoise(this.ctx, 10, 0x9e37_79b9);
  }

  /** The shared white-noise bed, for callers that build live graphs. */
  get white(): AudioBuffer { this.ensureNoiseBeds(); return this.whiteBuf!; }
  /** The shared pink-noise bed (10 s, Voss-McCartney). */
  get pink(): AudioBuffer { this.ensureNoiseBeds(); return this.pinkBuf!; }

  private async bakeOne(spec: SoundSpec): Promise<BakedSound> {
    const rate = this.ctx.sampleRate;
    const channels = spec.channels ?? 1;
    const length = Math.max(128, Math.ceil(spec.seconds * rate));
    const buffers: AudioBuffer[] = [];

    // Variants render IN PARALLEL. They are independent by construction — each
    // gets its own context and its own seeded RNG — and awaiting them one at a
    // time serialises 142 round-trips to the audio thread for no reason. The
    // richer recipes pushed the bank's bake from 0.4 s to 2.0 s, and every
    // millisecond of that is a millisecond of loading screen.
    const OC = typeof OfflineAudioContext !== 'undefined' ? OfflineAudioContext : null;
    // Resolved ONCE for the whole spec, never per variant: a sound must be
    // wholly recorded or wholly synthesised. Mixing the two across variants of
    // one id means every few shots the weapon changes character, which reads as
    // a bug rather than as variety.
    const takes = spec.sample !== undefined ? this.samples.count(spec.sample) : 0;
    const jobs: Array<Promise<AudioBuffer | null>> = [];
    for (let v = 0; v < Math.max(1, spec.variants) && OC !== null; v++) {
      const oc = new OC(channels, length, rate);
      // The offline context is a different BaseAudioContext, so the shared noise
      // beds have to be re-wrapped for it. Same Float32Array, no copy.
      const kit: BakeKit = {
        oc,
        white: rewrap(oc, this.whiteBuf!),
        pink: rewrap(oc, this.pinkBuf!),
        out: makeBakeBus(oc, spec),
        rng: makeRng(hashId(spec.id) ^ ((v + 1) * 0x9e3779b9)),
        variant: v,
      };
      const index = v;
      jobs.push((async (): Promise<AudioBuffer | null> => {
        try {
          const take = takes > 0 ? this.samples.get(spec.sample!, index) : null;
          if (take !== null) {
            sampleInto(kit, rewrap(oc, take), spec.sampleDb ?? 0, variantDetune(index, takes));
          } else {
            spec.render(kit);
          }
          return await oc.startRendering();
        } catch (err) {
          console.warn(`[audio] bake failed for "${spec.id}" variant ${index}`, err);
          return null;
        }
      })());
    }
    // `Promise.all` preserves order, so variant N is always buffers[N] and the
    // round-robin cursor still walks them in the authored sequence.
    for (const buf of await Promise.all(jobs)) {
      if (buf === null) continue;
      buffers.push(buf);
      this.stats.bytes += buf.length * buf.numberOfChannels * 4;
    }

    // Normalise the whole variant set to a peak of 1.0.
    //
    // A recipe's internal layer levels ("crack -4 dB, body -3 dB, tail -16 dB")
    // describe the BALANCE BETWEEN LAYERS; they say nothing about where the sum
    // lands, and four layers at -4 dB sum well past unity. Without this the
    // spec's `db` is applied on top of an already-clipping buffer and the
    // documented "peak dBFS at the bus input" is a fiction — measured peaks ran
    // 0.09 to 2.84 across the bank before this pass.
    //
    // Scaling by ONE factor across every variant preserves the deliberate
    // +-1.5 dB per-variant jitter that stops repeats sounding identical.
    if (spec.normalize !== false && buffers.length > 0) {
      let peak = 0;
      for (const b of buffers) {
        for (let c = 0; c < b.numberOfChannels; c++) {
          const d = b.getChannelData(c);
          for (let i = 0; i < d.length; i++) {
            const a = d[i] < 0 ? -d[i] : d[i];
            if (a > peak) peak = a;
          }
        }
      }
      if (peak > 1e-6 && Math.abs(peak - 1) > 0.01) {
        const k = 1 / peak;
        for (const b of buffers) {
          for (let c = 0; c < b.numberOfChannels; c++) {
            const d = b.getChannelData(c);
            for (let i = 0; i < d.length; i++) d[i] *= k;
          }
        }
      }
    }

    this.stats.baked += buffers.length;
    return {
      spec,
      buffers,
      cursor: 0,
      windowStart: -1,
      windowCount: 0,
      windowX: 0, windowY: 0, windowZ: 0,
      volleyEmitted: false,
    };
  }

  /* ---------------------------------------------------------------------- */
  /* Playback                                                               */
  /* ---------------------------------------------------------------------- */

  /**
   * Fire a one-shot. `x/y/z` are world metres; omit them for a UI blip.
   * Returns false when the sound was culled, stolen away or folded into a
   * volley — callers must not treat that as an error.
   */
  play(id: string, x?: number, y?: number, z?: number, opts?: PlayOptions): boolean {
    // A suspended context has a FROZEN currentTime. Every source scheduled
    // against it would fire simultaneously the instant the user first clicks —
    // a two-minute battle detonating in one frame. Drop instead.
    if (this.muted || this.disposed || this.ctx.state !== 'running') return false;
    const baked = this.sounds.get(id);
    if (baked === undefined || baked.buffers.length === 0) return false;
    const spec = baked.spec;
    const positional = spec.positional !== false && x !== undefined;

    /* -- crowd summation (§3.1) ------------------------------------------ */
    if (positional && spec.noCrowd !== true) {
      const t = this.now();
      if (baked.windowStart < 0 || t - baked.windowStart > AUDIO_CROWD.windowSec) {
        baked.windowStart = t;
        baked.windowCount = 0;
        baked.windowX = 0; baked.windowY = 0; baked.windowZ = 0;
        baked.volleyEmitted = false;
      }
      baked.windowCount++;
      baked.windowX += x!; baked.windowY += y ?? 0; baked.windowZ += z ?? 0;
      if (baked.windowCount >= AUDIO_CROWD.threshold) {
        if (baked.volleyEmitted) return false;
        baked.volleyEmitted = true;
        this.stats.crowded++;
        const n = baked.windowCount;
        const cx = baked.windowX / n, cy = baked.windowY / n, cz = baked.windowZ / n;
        const boost = 1 + AUDIO_CROWD.boost * Math.log(n);
        for (let i = 0; i < AUDIO_CROWD.smearMs.length; i++) {
          const tapGain = boost * (i === 0 ? 1 : 0.55 / i);
          this.emit(baked, cx, cy, cz, true, {
            gain: (opts?.gain ?? 1) * tapGain,
            delay: (opts?.delay ?? 0) + AUDIO_CROWD.smearMs[i] / 1000,
            // Widen the volley: alternate the taps around the centroid.
            pan: undefined,
          });
        }
        return true;
      }
    }

    return this.emit(baked, x ?? 0, y ?? 0, z ?? 0, positional, opts);
  }

  /** Non-positional convenience — UI blips, mono, centred, no distance. */
  ui(id: string, opts?: PlayOptions): boolean {
    return this.play(id, undefined, undefined, undefined, opts);
  }

  private emit(
    baked: BakedSound, x: number, y: number, z: number, positional: boolean, opts?: PlayOptions,
  ): boolean {
    const spec = baked.spec;
    const ctx = this.ctx;

    let g = dbToGain(spec.db) * (opts?.gain ?? 1);
    let pan = opts?.pan ?? 0;
    let lpHz = 0;
    let hpHz = 0;
    let sendDb = spec.sendDb ?? -200;

    if (positional) {
      const s = this.spatial(x, y, z);
      g *= s.gain;
      if (opts?.pan === undefined) pan = s.pan;
      lpHz = s.lpHz;
      hpHz = s.hpHz;
      if (sendDb > -200) sendDb = Math.min(sendDb, s.sendDb);
      else sendDb = s.sendDb;
    }

    // Pre-cull. Cheaper than any node allocation, and the single biggest win in
    // a 200-unit battle where most of the map is off-screen.
    if (g < dbToGain(AUDIO_CULL_DB)) { this.stats.culled++; return false; }

    if (!this.claimVoice(spec.category, g)) return false;

    const when = this.now() + Math.max(0, opts?.delay ?? 0);
    const src = ctx.createBufferSource();
    src.buffer = baked.buffers[baked.cursor % baked.buffers.length];
    baked.cursor++;
    const jitter = spec.rateJitter ?? 0;
    src.playbackRate.value = opts?.rate ?? (jitter > 0 ? 1 + (Math.random() * 2 - 1) * jitter : 1);
    if (opts?.detune) src.detune.value = opts.detune;

    const amp = gain(ctx, g);
    let tail: AudioNode = amp;
    src.connect(amp);

    // Distance tone shaping is only worth two more nodes when it is audible.
    if (positional && lpHz < AUDIO_DISTANCE.lpMaxHz * 0.92) {
      const lp = biquad(ctx, 'lowpass', lpHz, 0.7);
      tail.connect(lp); tail = lp;
      // Below ~4 kHz a single 12 dB/oct pole is not enough to read as DISTANCE
      // rather than as a tone control — the far tank still sounds like a near
      // tank turned down. Cascade a second pole there, and only there: it costs
      // one node on the sounds already far enough for it to matter.
      if (lpHz < 4000) {
        const lp2 = biquad(ctx, 'lowpass', lpHz * 1.15, 0.6);
        tail.connect(lp2); tail = lp2;
      }
    }
    if (positional && hpHz > AUDIO_DISTANCE.hpMinHz + 12) {
      const hp = biquad(ctx, 'highpass', hpHz, 0.7);
      tail.connect(hp); tail = hp;
    }

    let out: AudioNode = tail;
    if (spec.positional !== false) {
      const p = ctx.createStereoPanner();
      p.pan.value = clamp(pan, -1, 1);
      tail.connect(p);
      out = p;
    }
    out.connect(this.busInput(spec.bus));

    if (sendDb > -60) {
      const send = gain(ctx, dbToGain(sendDb));
      out.connect(send).connect(spec.reverb === 'wide' ? this.wideSend : this.reverbSend);
    }

    const voice: Voice = {
      src, amp, category: spec.category, startedAt: when, finalGain: g, stolen: false,
    };
    this.voices.push(voice);
    this.stats.oneShots = this.voices.length;

    src.onended = () => this.releaseVoice(voice);
    try { src.start(when); } catch { this.releaseVoice(voice); return false; }
    return true;
  }

  /**
   * Play an already-baked buffer through a bus without registering a spec.
   * EVA lines and barks use this: they are baked per line, not per recipe.
   */
  playBuffer(
    buffer: AudioBuffer, bus: BusName, category: VoiceCategory, db: number,
    through: AudioNode | null = null, opts?: PlayOptions,
  ): { source: AudioBufferSourceNode; amp: GainNode } | null {
    if (this.muted || this.disposed || this.ctx.state !== 'running') return null;
    if (!this.claimVoice(category, dbToGain(db))) return null;
    const ctx = this.ctx;
    const src = ctx.createBufferSource();
    src.buffer = buffer;
    if (opts?.rate) src.playbackRate.value = opts.rate;
    if (opts?.detune) src.detune.value = opts.detune;
    const amp = gain(ctx, dbToGain(db) * (opts?.gain ?? 1));
    src.connect(amp);
    if (through !== null) amp.connect(through);
    else amp.connect(this.busInput(bus));

    const voice: Voice = {
      src, amp, category, startedAt: this.now(), finalGain: amp.gain.value, stolen: false,
    };
    this.voices.push(voice);
    src.onended = () => this.releaseVoice(voice);
    try { src.start(this.now() + Math.max(0, opts?.delay ?? 0)); } catch {
      this.releaseVoice(voice);
      return null;
    }
    return { source: src, amp };
  }

  /* ---------------------------------------------------------------------- */
  /* Voice budget                                                           */
  /* ---------------------------------------------------------------------- */

  /**
   * Reserve a slot, stealing if the category or the global cap is full.
   * Stealing picks the QUIETEST voice first and the oldest as a tie-break, so a
   * big close explosion never loses its slot to a distant rifle round.
   */
  private claimVoice(category: VoiceCategory, wantGain: number): boolean {
    const cap = AUDIO_VOICE_CAPS[category] ?? AUDIO_VOICE_CAPS.misc;
    const inCat = this.categoryCount.get(category) ?? 0;

    if (inCat >= cap) {
      const victim = this.pickVictim(category);
      if (victim === null || victim.finalGain > wantGain * 1.6) return false;
      this.killVoice(victim, AUDIO_STEAL_RAMP_MS);
    } else if (this.voices.length >= AUDIO_MAX_ONESHOTS) {
      const victim = this.pickVictim(null);
      if (victim === null) return false;
      this.killVoice(victim, AUDIO_STEAL_RAMP_MS);
    }

    this.categoryCount.set(category, (this.categoryCount.get(category) ?? 0) + 1);
    return true;
  }

  private pickVictim(category: VoiceCategory | null): Voice | null {
    let best: Voice | null = null;
    for (let i = 0; i < this.voices.length; i++) {
      const v = this.voices[i];
      if (v.stolen) continue;
      if (category !== null && v.category !== category) continue;
      if (best === null) { best = v; continue; }
      if (v.finalGain < best.finalGain - 1e-4) { best = v; continue; }
      if (Math.abs(v.finalGain - best.finalGain) <= 1e-4 && v.startedAt < best.startedAt) best = v;
    }
    return best;
  }

  private killVoice(v: Voice, rampMs: number): void {
    if (v.stolen) return;
    v.stolen = true;
    this.stats.stolen++;
    const t = this.now();
    const r = Math.max(0.001, rampMs / 1000);
    try {
      v.amp.gain.cancelScheduledValues(t);
      v.amp.gain.setValueAtTime(Math.max(0.0001, v.amp.gain.value), t);
      v.amp.gain.exponentialRampToValueAtTime(0.0001, t + r);
      v.amp.gain.setValueAtTime(0, t + r);
      v.src.stop(t + r + 0.002);
    } catch { /* the source may already have ended */ }
  }

  private releaseVoice(v: Voice): void {
    const i = this.voices.indexOf(v);
    if (i < 0) return;
    this.voices[i] = this.voices[this.voices.length - 1];
    this.voices.pop();
    this.categoryCount.set(v.category, Math.max(0, (this.categoryCount.get(v.category) ?? 1) - 1));
    this.stats.oneShots = this.voices.length;
    try { v.src.disconnect(); v.amp.disconnect(); } catch { /* already gone */ }
  }

  /* ---------------------------------------------------------------------- */
  /* Loops                                                                  */
  /* ---------------------------------------------------------------------- */

  /**
   * Open a live loop strip. The caller wires its own sources into `input` and
   * registers them so the engine can stop and detune them.
   *
   * Returns null when the loop budget is exhausted — a caller that ignores the
   * null gets a silent loop, not a crash.
   */
  openLoop(bus: BusName, startGain = 0, positional = true): LoopVoice | null {
    if (this.muted || this.disposed) return null;
    if (this.loops.length >= AUDIO_MAX_LOOPS) return null;
    const ctx = this.ctx;
    const input = gain(ctx, 1);
    const amp = gain(ctx, startGain);
    input.connect(amp);
    let panner: StereoPannerNode | null = null;
    if (positional) {
      panner = ctx.createStereoPanner();
      amp.connect(panner);
      panner.connect(this.busInput(bus));
    } else {
      amp.connect(this.busInput(bus));
    }
    const loop = new LoopVoice(this, input, amp, panner, [], []);
    this.loops.push(loop);
    this.stats.loops = this.loops.length;
    return loop;
  }

  /** Register a source with an open loop so `stop`/`setDetune` reach it. */
  attachLoopSource(loop: LoopVoice, src: AudioScheduledSourceNode): void {
    loop.sources.push(src);
  }

  /** Register a node the caller wants to reach later via `loop.node(i)`. */
  attachLoopNode(loop: LoopVoice, node: AudioNode): number {
    loop.extra.push(node);
    return loop.extra.length - 1;
  }

  /** Called by LoopVoice.stop; do not call directly. */
  retireLoop(loop: LoopVoice, afterMs: number): void {
    setTimeout(() => {
      const i = this.loops.indexOf(loop);
      if (i >= 0) {
        this.loops[i] = this.loops[this.loops.length - 1];
        this.loops.pop();
        this.stats.loops = this.loops.length;
      }
      try { loop.input.disconnect(); loop.amp.disconnect(); } catch { /* gone */ }
    }, Math.max(0, afterMs));
  }

  /* ---------------------------------------------------------------------- */
  /* Reverb theatre                                                         */
  /* ---------------------------------------------------------------------- */

  /** Build every convolver's impulse response. Call once, awaited, at init. */
  async initReverb(theatre: keyof typeof AUDIO_REVERB = 'temperate'): Promise<void> {
    const ir = await this.makeImpulse(theatre, 1);
    if (ir === null) return;
    this.convolverA.buffer = ir;
    this.convolverB.buffer = ir;
    this.theatre = theatre;
    this.reverbReturn.gain.value = dbToGain(AUDIO_REVERB[theatre].returnDb);
    const wide = await this.makeImpulse(theatre, WIDE_RT_SCALE);
    if (wide !== null) this.wideConv.buffer = wide;
  }

  /** Crossfade to another environment over 2 s. Safe to call every frame. */
  async setTheatre(theatre: keyof typeof AUDIO_REVERB): Promise<void> {
    if (this.disposed || theatre === this.theatre) return;
    const ir = await this.makeImpulse(theatre, 1);
    if (ir === null) return;
    this.theatre = theatre;
    // The wide room has no crossfade pair: it is only ever heard under an
    // explosion, and a swap mid-tail is masked by the boom that caused it.
    void this.makeImpulse(theatre, WIDE_RT_SCALE).then((w) => {
      if (w !== null && !this.disposed) this.wideConv.buffer = w;
    });
    const t = this.now();
    const fade = AUDIO_REVERB_CROSSFADE_SEC;
    if (this.convUsingA) {
      this.convolverB.buffer = ir;
      this.convGainB.gain.setValueAtTime(this.convGainB.gain.value, t);
      this.convGainB.gain.linearRampToValueAtTime(1, t + fade);
      this.convGainA.gain.setValueAtTime(this.convGainA.gain.value, t);
      this.convGainA.gain.linearRampToValueAtTime(0, t + fade);
    } else {
      this.convolverA.buffer = ir;
      this.convGainA.gain.setValueAtTime(this.convGainA.gain.value, t);
      this.convGainA.gain.linearRampToValueAtTime(1, t + fade);
      this.convGainB.gain.setValueAtTime(this.convGainB.gain.value, t);
      this.convGainB.gain.linearRampToValueAtTime(0, t + fade);
    }
    this.convUsingA = !this.convUsingA;
    this.reverbReturn.gain.setTargetAtTime(dbToGain(AUDIO_REVERB[theatre].returnDb), t, 0.4);
  }

  /**
   * Procedural stereo IR with FREQUENCY-DEPENDENT DECAY.
   *
   * The raw buffer is flat decorrelated noise with a diffusion ramp and the
   * discrete early taps stamped on; the decay is then applied by three parallel
   * filter bands, each with its own exponential envelope (`IR_BAND_DECAY`). Bass
   * rings for the full RT60, treble is gone in under half of it — which is what
   * a field, a street or a snowfield actually does.
   *
   * The previous single-envelope version decayed every frequency at one rate,
   * and the result read as "a burst of noise stuck to the end of the sound"
   * rather than as a room. That is the difference this function exists for.
   *
   * The two channels use INDEPENDENT noise seeds; that decorrelation is the
   * entire stereo width, and it costs nothing.
   *
   * @param scale  Multiplies the decay. 1 is the close room, `WIDE_RT_SCALE`
   *               the explosion room.
   */
  private async makeImpulse(
    theatre: keyof typeof AUDIO_REVERB, scale: number,
  ): Promise<AudioBuffer | null> {
    const OC = typeof OfflineAudioContext !== 'undefined' ? OfflineAudioContext : null;
    if (OC === null) return null;
    const cfg = AUDIO_REVERB[theatre];
    const rate = this.ctx.sampleRate;
    const rt = cfg.rt60 * scale;
    const n = Math.max(256, Math.ceil(rt * rate));
    const oc = new OC(2, n, rate);
    const raw = oc.createBuffer(2, n, rate);
    const pre = Math.floor(((cfg.preDelayMs * Math.sqrt(scale)) / 1000) * rate);

    for (let ch = 0; ch < 2; ch++) {
      const d = raw.getChannelData(ch);
      const rng = makeRng(0xa11ce + ch * 977 + hashId(theatre) + Math.round(scale * 1000));
      // Diffusion: a real tail is sparse at first and dense later. Ramping the
      // noise density over the first 12% is what stops the IR sounding like a
      // gate opening on a hiss generator.
      const diffuse = Math.max(1, Math.floor((n - pre) * 0.12));
      for (let i = pre; i < n; i++) {
        const k = i - pre;
        const density = k < diffuse ? 0.25 + 0.75 * (k / diffuse) : 1;
        d[i] = rng() < density ? rng() * 2 - 1 : 0;
      }
      const tapGains = [0.75, 0.52, 0.38, 0.27];
      for (let k = 0; k < cfg.taps.length; k++) {
        const idx = pre + Math.floor(((cfg.taps[k] * Math.sqrt(scale)) / 1000) * rate);
        if (idx < n) d[idx] += (k % 2 === 0 ? 1 : -1) * (tapGains[k] ?? 0.2);
      }
    }

    const src = oc.createBufferSource();
    src.buffer = raw;
    src.start(0);

    const bands: Array<[BiquadFilterType, number, number]> = [
      ['lowpass', 320, 0.6],
      ['bandpass', 1100, 0.55],
      ['highpass', 2600, 0.6],
    ];
    for (let b = 0; b < bands.length; b++) {
      const [type, hz, q] = bands[b];
      const f = biquad(oc, type, hz, q);
      // The damping corner still applies on top: snow eats treble, a street
      // does not, and that is what `dampHz` means.
      const damp = biquad(oc, 'lowpass', cfg.dampHz, 0.7);
      const g = gain(oc, b === 1 ? 0.9 : 0.75);
      const decay = Math.max(0.05, rt * IR_BAND_DECAY[b]);
      g.gain.setValueAtTime(g.gain.value, 0);
      g.gain.exponentialRampToValueAtTime(0.0001, decay);
      src.connect(f).connect(damp).connect(g).connect(oc.destination);
    }

    try {
      return await oc.startRendering();
    } catch (err) {
      console.warn('[audio] impulse render failed', err);
      return null;
    }
  }
}

/* ==========================================================================
 * 8. UTILITIES
 * ========================================================================== */

/**
 * Re-wrap a shared noise bed for another BaseAudioContext.
 *
 * `AudioBuffer`s are not portable between contexts, but the underlying
 * Float32Array is — so this hands the same samples to the offline renderer
 * without regenerating 480 000 values per bake.
 */
/**
 * The node a recipe's layers connect to (`kit.out`).
 *
 * With `drive` set this is `gain -> saturator -> DC-blocking highpass ->
 * destination`. The trim in front matters: the saturator's knee is fixed, so
 * the only way to control HOW HARD a sum hits it is to set the level going in,
 * and a recipe whose layers already sum past unity would otherwise be squared
 * off regardless of its `drive` value. -6 dB in, +5.2 dB out keeps the stage
 * roughly unity-gain so the peak normaliser downstream has little to do.
 *
 * The highpass at 18 Hz removes the DC offset the asymmetric curve introduces.
 * Left in, that offset eats headroom in the master limiter for no audible
 * return, and it makes every buffer's measured peak a lie.
 */
export function makeBakeBus(oc: OfflineAudioContext, spec: SoundSpec): AudioNode {
  const k = spec.drive ?? 0;
  if (k <= 0) return oc.destination;
  const input = gain(oc, dbToGain(-6));
  // 4x oversampling runs the whole graph at 192 kHz through the shaper, and on
  // a 3.2 s explosion that is most of the bake budget: measured, the bank went
  // from 0.4 s to 2.0 s of offline rendering, which is 1.6 s added to a loading
  // screen to suppress fold-back nobody can hear. Long recipes get 2x; the
  // short bright ones, where the aliasing WOULD sit in the audible band, keep 4x.
  const sat = saturator(oc, k, spec.driveAsym ?? 0.12, spec.seconds > 0.9 ? '2x' : '4x');
  const dc = biquad(oc, 'highpass', 18, 0.5);
  const makeup = gain(oc, dbToGain(5.2));
  input.connect(sat).connect(dc).connect(makeup).connect(oc.destination);
  return input;
}

/**
 * Move an AudioBuffer between contexts. Exported for `tools/audio-probe.ts`,
 * which has to reproduce `bakeOne` exactly to measure what actually ships.
 */
export function rewrap(oc: BaseAudioContext, src: AudioBuffer): AudioBuffer {
  if (src.sampleRate === oc.sampleRate) {
    const out = oc.createBuffer(src.numberOfChannels, src.length, src.sampleRate);
    for (let c = 0; c < src.numberOfChannels; c++) out.copyToChannel(src.getChannelData(c), c);
    return out;
  }
  // Different rate: nearest-neighbour is fine for noise, which has no phase.
  const ratio = oc.sampleRate / src.sampleRate;
  const n = Math.max(1, Math.floor(src.length * ratio));
  const out = oc.createBuffer(src.numberOfChannels, n, oc.sampleRate);
  for (let c = 0; c < src.numberOfChannels; c++) {
    const s = src.getChannelData(c);
    const d = out.getChannelData(c);
    for (let i = 0; i < n; i++) d[i] = s[Math.min(s.length - 1, Math.floor(i / ratio))];
  }
  return out;
}

/**
 * Peak-normalise a rendered buffer in place. Voice lines need this as much as
 * one-shots do: a line with three /s/ in it sums much hotter than one without,
 * and the announcer must be at ONE level regardless of what it is saying.
 */
export function normalizeBuffer(buf: AudioBuffer, target = 1): void {
  let peak = 0;
  for (let c = 0; c < buf.numberOfChannels; c++) {
    const d = buf.getChannelData(c);
    for (let i = 0; i < d.length; i++) {
      const a = d[i] < 0 ? -d[i] : d[i];
      if (a > peak) peak = a;
    }
  }
  if (peak <= 1e-6) return;
  const k = target / peak;
  if (Math.abs(k - 1) < 0.01) return;
  for (let c = 0; c < buf.numberOfChannels; c++) {
    const d = buf.getChannelData(c);
    for (let i = 0; i < d.length; i++) d[i] *= k;
  }
}

/** FNV-1a over a sound id, so a bake seed is stable across reloads. */
export function hashId(s: string): number {
  let h = 0x811c9dc5;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 0x01000193);
  }
  return h >>> 0;
}

/**
 * One frame of breathing room during the bake.
 *
 * rAF is RACED against a timer, never awaited alone: a backgrounded tab never
 * fires rAF, so a bake that yields purely on rAF hangs forever — and because
 * `registry.init()` awaits it, the whole game would fail to boot for anyone who
 * alt-tabs during the loading screen. Whichever fires first wins.
 */
function isHidden(): boolean {
  return typeof document !== 'undefined' && document.hidden === true;
}

function nextFrame(): Promise<void> {
  return new Promise((resolve) => {
    let done = false;
    const finish = (): void => { if (!done) { done = true; resolve(); } };
    if (typeof requestAnimationFrame === 'function') requestAnimationFrame(finish);
    setTimeout(finish, 34);
  });
}

/* ==========================================================================
 * 9. THE MODULE FACADE
 *
 * `audio.system.ts` installs the live implementation here so any module can
 * `import { play, eva, setCombatIntensity } from '../audio/AudioEngine'` without
 * importing a system file or creating a cycle. Every call is a safe no-op until
 * the audio module has booted.
 * ========================================================================== */

export interface AudioFacade {
  play(id: string, x?: number, y?: number, z?: number, gain?: number): void;
  ui(id: string): void;
  eva(line: string): void;
  bark(unitClass: string, category: string, x?: number, y?: number, z?: number): void;
  setCombatIntensity(v: number): void;
  readonly engine: AudioEngine | null;
}

let facade: AudioFacade | null = null;

/** Installed once by audio.system.ts. Pass null on teardown. */
export function setAudioFacade(f: AudioFacade | null): void {
  facade = f;
}

/** The live facade, or null before the audio module has initialised. */
export function audio(): AudioFacade | null {
  return facade;
}

/** Positional one-shot by sound id. No-op until audio boots. */
export function play(id: string, x?: number, y?: number, z?: number, gain?: number): void {
  facade?.play(id, x, y, z, gain);
}

/** Non-positional UI blip. */
export function playUi(id: string): void {
  facade?.ui(id);
}

/** Queue an EVA announcer line by id (see Eva.ts EVA_LINES). */
export function eva(line: string): void {
  facade?.eva(line);
}

/** 0..1 combat intensity driving the music layer crossfade. */
export function setCombatIntensity(v: number): void {
  facade?.setCombatIntensity(v);
}
