/**
 * ============================================================================
 * VOLTMARCH — src/audio/TrackMusic.ts
 * ============================================================================
 * ORIGINAL RECORDED SCORE. The four cues are user-supplied VOLTMARCH masters,
 * generated by the project owner with a paid Suno Pro account and prepared by
 * `tools/prepare-music.py`. They are streamed one at a time: a multi-minute
 * stereo soundtrack must never become hundreds of megabytes of decoded PCM.
 *
 * The title screen always opens on Echoes of the Siege with a slow fade-in. A
 * match then chooses any cue at random and loops it for the whole battle. Music
 * is presentation, not simulation, so the choice deliberately uses local
 * entropy and never enters the lockstep command stream. Manual previous/next
 * controls use the same player from both the title and pause menus.
 * ============================================================================
 */

import type { AudioEngine, MusicTrackSnapshot } from './AudioEngine';
import { MusicDirector } from './Music';

export interface SoundtrackCue {
  readonly id: string;
  readonly title: string;
  readonly file: string;
}

export const SOUNDTRACK = [
  { id: 'silent-horizon', title: 'Silent Horizon', file: 'silent-horizon.ogg' },
  { id: 'disciplined-ostinato', title: 'Disciplined Ostinato', file: 'disciplined-ostinato.ogg' },
  { id: 'echoes-of-the-siege', title: 'Echoes of the Siege', file: 'echoes-of-the-siege.ogg' },
  { id: 'endless-warfront', title: 'Endless Warfront', file: 'endless-warfront.ogg' },
] as const satisfies readonly SoundtrackCue[];

export const MUSIC_TRACK_EVENT = 'voltmarch:music-track';
export const MENU_SOUNDTRACK_ID = 'echoes-of-the-siege';
export const MENU_SOUNDTRACK_INDEX = SOUNDTRACK.findIndex((cue) => cue.id === MENU_SOUNDTRACK_ID);

const MUSIC_DIR = 'audio/music';
const SWITCH_FADE_SEC = 0.24;
const MENU_FADE_SEC = 2.5;
const RETRY_MS = 500;

export function musicPath(file: string): string {
  return `${MUSIC_DIR}/${file}`;
}

/** Random index that does not immediately repeat the current cue. */
export function chooseRandomTrack(current: number, random = Math.random): number {
  if (SOUNDTRACK.length <= 1) return 0;
  if (current < 0 || current >= SOUNDTRACK.length) {
    return Math.min(SOUNDTRACK.length - 1, Math.floor(random() * SOUNDTRACK.length));
  }
  const candidate = Math.min(SOUNDTRACK.length - 2, Math.floor(random() * (SOUNDTRACK.length - 1)));
  return candidate >= current ? candidate + 1 : candidate;
}

export class TrackMusic {
  private readonly engine: AudioEngine;
  private element: HTMLAudioElement | null = null;
  private gain: GainNode | null = null;
  private fallback: MusicDirector | null = null;
  private retryTimer: ReturnType<typeof setInterval> | null = null;
  private switchTimer: ReturnType<typeof setTimeout> | null = null;
  private started = false;
  private disposed = false;
  private index = -1;
  private heatRaw = 0;
  private switchGeneration = 0;
  private userPaused = false;

  constructor(engine: AudioEngine) {
    this.engine = engine;
  }

  start(): void {
    if (this.started || this.disposed || this.engine.muted) return;
    this.started = true;

    if (typeof Audio === 'undefined' || typeof this.engine.ctx.createMediaElementSource !== 'function') {
      this.useFallback('no HTMLAudioElement or MediaElementSource on this platform');
      return;
    }

    try {
      const element = new Audio();
      element.loop = true;
      // The title cue is a first-screen asset, not optional metadata. The HTML
      // preload starts its request before modules parse; `auto` lets this same
      // element consume the body immediately instead of issuing a range fetch
      // now and stalling again on the first play(). Only one cue is loaded.
      element.preload = 'auto';
      element.addEventListener('error', () => {
        const cue = SOUNDTRACK[this.index];
        this.useFallback(`cue "${cue?.title ?? 'unknown'}" failed to load`);
      });

      const source = this.engine.ctx.createMediaElementSource(element);
      const gain = this.engine.ctx.createGain();
      gain.gain.value = 1;
      source.connect(gain).connect(this.engine.musicOut());
      this.element = element;
      this.gain = gain;
    } catch (err) {
      this.useFallback(`could not build the stream graph: ${String(err)}`);
      return;
    }

    this.switchTo(MENU_SOUNDTRACK_INDEX, true, MENU_FADE_SEC);
    this.retryTimer = setInterval(() => this.ensurePlaying(), RETRY_MS);
  }

  /** Select from all four cues exactly once when a real match begins. */
  startMatch(): void {
    if (this.fallback !== null) return;
    this.switchTo(chooseRandomTrack(-1));
  }

  /** Restore the title cue when returning from a match or another shell route. */
  playMenu(): void {
    if (this.fallback !== null || this.index === MENU_SOUNDTRACK_INDEX) return;
    this.switchTo(MENU_SOUNDTRACK_INDEX);
  }

  next(): void {
    if (this.fallback !== null) return;
    this.switchTo((Math.max(0, this.index) + 1) % SOUNDTRACK.length);
  }

  previous(): void {
    if (this.fallback !== null) return;
    this.switchTo((Math.max(0, this.index) - 1 + SOUNDTRACK.length) % SOUNDTRACK.length);
  }

  togglePaused(): void {
    this.userPaused = !this.userPaused;
    if (this.fallback !== null) {
      if (this.userPaused) this.fallback.pause();
      else this.fallback.resume();
    } else if (this.element !== null) {
      if (this.userPaused) this.element.pause();
      else this.ensurePlaying();
    }
    this.emitTrack();
  }

  private switchTo(index: number, immediate = false, fadeInSec = immediate ? 0 : SWITCH_FADE_SEC): void {
    const element = this.element;
    const gain = this.gain;
    const cue = SOUNDTRACK[index];
    if (element === null || gain === null || cue === undefined || this.disposed) return;

    const generation = ++this.switchGeneration;
    if (this.switchTimer !== null) {
      clearTimeout(this.switchTimer);
      this.switchTimer = null;
    }

    const load = (): void => {
      if (this.disposed || generation !== this.switchGeneration) return;
      this.index = index;
      element.pause();
      element.src = musicPath(cue.file);
      element.currentTime = 0;
      element.load();

      const t = this.engine.now();
      gain.gain.cancelScheduledValues(t);
      gain.gain.setValueAtTime(fadeInSec > 0 ? 0.0001 : 1, t);
      if (fadeInSec > 0) gain.gain.linearRampToValueAtTime(1, t + fadeInSec);
      this.emitTrack();
      this.ensurePlaying();
    };

    if (immediate) {
      load();
      return;
    }

    const t = this.engine.now();
    gain.gain.cancelScheduledValues(t);
    gain.gain.setValueAtTime(Math.max(0.0001, gain.gain.value), t);
    gain.gain.setTargetAtTime(0.0001, t, SWITCH_FADE_SEC / 3);
    this.switchTimer = setTimeout(load, SWITCH_FADE_SEC * 1000 + 30);
  }

  private ensurePlaying(): void {
    const element = this.element;
    if (element === null || this.userPaused || !this.engine.running || !element.paused) return;
    void element.play().catch(() => { /* context still locked; retry on the timer */ });
  }

  private emitTrack(): void {
    if (typeof globalThis.dispatchEvent !== 'function' || typeof CustomEvent !== 'function') return;
    const snapshot = this.snapshot;
    if (snapshot === null) return;
    globalThis.dispatchEvent(new CustomEvent<MusicTrackSnapshot>(MUSIC_TRACK_EVENT, {
      detail: snapshot,
    }));
  }

  private useFallback(why: string): void {
    if (this.fallback !== null || this.disposed) return;
    console.warn(`[music] original score unavailable — ${why}; using the procedural sequencer`);
    this.clearTimers();
    if (this.element !== null) {
      try { this.element.pause(); this.element.src = ''; } catch { /* already gone */ }
    }
    try { this.gain?.disconnect(); } catch { /* already gone */ }
    this.element = null;
    this.gain = null;
    this.fallback = new MusicDirector(this.engine);
    this.fallback.start();
    this.fallback.primeHeat(this.heatRaw);
    if (this.userPaused) this.fallback.pause();
  }

  private clearTimers(): void {
    if (this.retryTimer !== null) { clearInterval(this.retryTimer); this.retryTimer = null; }
    if (this.switchTimer !== null) { clearTimeout(this.switchTimer); this.switchTimer = null; }
  }

  stop(fadeSec = 1.5): void {
    if (this.fallback !== null) { this.fallback.stop(fadeSec); return; }
    const element = this.element;
    const gain = this.gain;
    if (element === null || gain === null) return;
    const t = this.engine.now();
    gain.gain.cancelScheduledValues(t);
    gain.gain.setValueAtTime(Math.max(0.0001, gain.gain.value), t);
    gain.gain.linearRampToValueAtTime(0, t + fadeSec);
    setTimeout(() => { try { element.pause(); } catch { /* gone */ } }, fadeSec * 1000 + 60);
  }

  dispose(): void {
    if (this.disposed) return;
    this.disposed = true;
    this.clearTimers();
    this.fallback?.dispose();
    if (this.element !== null) {
      try { this.element.pause(); this.element.src = ''; } catch { /* gone */ }
    }
    try { this.gain?.disconnect(); } catch { /* gone */ }
    this.element = null;
    this.gain = null;
  }

  setCombatHeat(h: number): void {
    this.heatRaw = h < 0 ? 0 : h > 1 ? 1 : h;
    this.fallback?.setCombatHeat(this.heatRaw);
  }

  primeHeat(h: number): void {
    this.heatRaw = h;
    this.fallback?.primeHeat(h);
  }

  // The original cues are complete compositions, not intensity stems. Match
  // outcomes leave the selected loop playing; EVA owns the audible verdict.
  win(): void { this.fallback?.win(); }
  loss(): void { this.fallback?.loss(); }

  get snapshot(): MusicTrackSnapshot | null {
    const cue = SOUNDTRACK[this.index];
    if (cue === undefined || this.fallback !== null) return null;
    return {
      id: cue.id,
      title: cue.title,
      index: this.index,
      total: SOUNDTRACK.length,
      paused: this.userPaused,
    };
  }

  get intensity(): number { return this.fallback?.intensity ?? this.heatRaw; }
  get rawHeat(): number { return this.fallback?.rawHeat ?? this.heatRaw; }
  get currentLayer(): number { return this.fallback?.currentLayer ?? Math.max(0, this.index); }
  get running(): boolean {
    if (this.fallback !== null) return this.fallback.running;
    return this.started && this.element !== null && !this.element.paused;
  }
  get scheduledSteps(): number {
    if (this.fallback !== null) return this.fallback.scheduledSteps;
    return this.element === null ? -1 : Math.round(this.element.currentTime * 10);
  }
  get recorded(): boolean { return this.fallback === null && this.element !== null; }
}
